### PR TITLE
[Hooks] Add a line number reference inside the build file.

### PR DESCRIPTION
**Pull request by zozoens31**
This change is [Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/381)

### CODE REVIEW

**Comment by zozoens31** [comment]
:game_die:

**Comment by zozoens31** [comment]
:rocket:

**Comment by zozoens31** [comment]
:rocket:

**Review by emilieguth — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/381#-:-MrWXzxHEv1y9qk_vDoX:bnfp4nl)* status: :shipit: complete! 0 of 1 files reviewed, all discussions resolved

**Pull request merged**
