### PR TITLE
[Clean Code] Update to use default branch instead of master in git submit

### PR DESCRIPTION
**Pull request by emilieguth**
This change is [Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/151)

### CODE REVIEW

**Review by emilieguth — COMMENTED** [review]
+reviewer:@pcorpet 

> *[Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/151#-:-MVqk8be2OYSarzPl2bv:b-4erzco)* status: LGTM missing from one of: zozoens31,pcorpet

**Review by pcorpet — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/151)* status: LGTM missing from one of: zozoens31, Unresolved discussions (bin/git-submit:r2 line 24)

___
*[bin/git-submit, line 24 at r2](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/151#-MW3_1MvATkVwsm47b55:-MW3_1MvATkVwsm47b56:b-4lvn8p) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/f4af86e729fb72cf405520dc7f60c8ed2abd52ca/bin/git-submit#L24)):*
> ```
> fi
> 
> readonly DEFAULT_BRANCH="$(git rev-parse --abbrev-ref "origin/HEAD" | cut -d/ -f2)"
> ```

Please comment this as being usually main (or previously master).
___
*[git-custom-commands-test/features/git-submit.feature, line 10 at r2](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/151#-MW3_gx23Dndq8cUGXiT:-MW3_gx23Dndq8cUGXiU:bjzpzeu) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/ca7558201703d887a78dcf75dbe5d3ff4f8e9c40/git-custom-commands-test/features/git-submit.feature#L10)):*
> ```Gherkin
>     Given a dummy git repo in "origin"
>     And I am in a "work" git repo cloned from "origin"
>     And I create a "success" git branch from "master"
> ```

I think this was way more easy to understand and was better to test. Please revert and use "main" instead of "master" and create only one scenario where you change the default branch.
___
*[git-custom-commands-test/features/support/env.rb, line 20 at r2](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/151#-MW3_ROx22ipAzeSWz8U:-MW3_ROx22ipAzeSWz8V:bx00hvn) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/f4af86e729fb72cf405520dc7f60c8ed2abd52ca/git-custom-commands-test/features/support/env.rb#L20)):*
> ```Ruby
> 
>   def git_default_branch()
>     default_branch = ''
> ```

This doesn't seem useful here as well.
___
*[git-custom-commands-test/features/support/env.rb, line 21 at r2](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/151#-MW3_O325qIyYPruEOKt:-MW3_O3349EDSbmcfkH9:bqa3mz5) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/f4af86e729fb72cf405520dc7f60c8ed2abd52ca/git-custom-commands-test/features/support/env.rb#L21)):*
> ```Ruby
>   def git_default_branch()
>     default_branch = ''
>     cd ('.') {
> ```

How is that useful?

**Review by emilieguth — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/151)* status: LGTM missing from one of: zozoens31

___
*[bin/git-submit, line 24 at r2](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/151#-MW3_1MvATkVwsm47b55:-MW3afe_CIPtyCt0CSfT:b-896fix) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/74bf28e21ea2f9a44578df1c92ae2df3786d565d/bin/git-submit#L24)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

Please comment this as being usually main (or previously master).
</blockquote></details>

Done.
___
*[git-custom-commands-test/features/git-submit.feature, line 10 at r2](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/151#-MW3_gx23Dndq8cUGXiT:-MW3b6_5183ErPy-PR97:b-896fix) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/e653da454d3c5c8ff10ce3ea55a8a2fbeb46d2db/git-custom-commands-test/features/git-submit.feature#L10)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

I think this was way more easy to understand and was better to test. Please revert and use "main" instead of "master" and create only one scenario where you change the default branch.
</blockquote></details>

Done.
___
*[git-custom-commands-test/features/support/env.rb, line 20 at r2](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/151#-MW3_ROx22ipAzeSWz8U:-MW3bosZ3NZtWlbyp9g_:b-896fix) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/74bf28e21ea2f9a44578df1c92ae2df3786d565d/git-custom-commands-test/features/support/env.rb#L20)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

This doesn't seem useful here as well.
</blockquote></details>

Done.
___
*[git-custom-commands-test/features/support/env.rb, line 21 at r2](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/151#-MW3_O325qIyYPruEOKt:-MW3bogU18x1Qqj-IwnV:b-896fix) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/74bf28e21ea2f9a44578df1c92ae2df3786d565d/git-custom-commands-test/features/support/env.rb#L21)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

How is that useful?
</blockquote></details>

Done.

**Review by emilieguth — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/151)* status: LGTM missing from one of: zozoens31

___
*[git-custom-commands-test/features/support/env.rb, line 21 at r2](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/151#-MW3_O325qIyYPruEOKt:-MW3hcJM-eDAAc1G5FJT:b-8p8ilg) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/74bf28e21ea2f9a44578df1c92ae2df3786d565d/git-custom-commands-test/features/support/env.rb#L21)):*
<details><summary><i>Previously, emilieguth (Émilie Guth) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I don't understand why it's not working if I remove these following lines. Do you have an idea?
```
default_branch = ''
cd ('.') {
}
```

**Review by pcorpet — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/151)* status: LGTM missing from one of: zozoens31, Unresolved discussions (bin/git-submit:r3 line 24)

___
*[bin/git-submit, line 24 at r3](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/151#-MW4_1uH4Fyuz2MxKfQg:-MW4_1uH4Fyuz2MxKfQh:btppje4) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/cd96f2364e0e6cbe09418e9b63ca0568d675c3a8/bin/git-submit#L24)):*
> ```
> fi
> 
> #Usually main (and previously master).
> ```

Please add a blank between `#` and `U`
___
*[git-custom-commands-test/features/git-submit.feature, line 18 at r3](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/151#-MW4_9Nw8nKc-PBgY8sP:-MW4_9Nw8nKc-PBgY8sQ:bqgxpx7) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/cd96f2364e0e6cbe09418e9b63ca0568d675c3a8/git-custom-commands-test/features/git-submit.feature#L18)):*
> ```Gherkin
>     When I run `git submit`
>     Then the exit status should be 0
>     And I should be on "default_branch" git branch
> ```

keep "main" here and below
___
*[git-custom-commands-test/features/steps.rb, line 17 at r3](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/151#-MW4_KTh2clFV-x-H9yn:-MW4_KTh2clFV-x-H9yo:bb76mu4) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/cd96f2364e0e6cbe09418e9b63ca0568d675c3a8/git-custom-commands-test/features/steps.rb#L17)):*
> ```Ruby
> 
> Given(/^I create a "([^"]+)" git branch from "([^"]+)"$/) do |branch_name, origin_branch|
>   if origin_branch == 'main'
> ```

Why?
___
*[git-custom-commands-test/features/support/env.rb, line 21 at r2](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/151#-MW3_O325qIyYPruEOKt:-MW4_N9M0-e0XswJBGLp:bmz4vpb) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/74bf28e21ea2f9a44578df1c92ae2df3786d565d/git-custom-commands-test/features/support/env.rb#L21)):*
<details><summary><i>Previously, emilieguth (Émilie Guth) wrote…</i></summary><blockquote>

I don't understand why it's not working if I remove these following lines. Do you have an idea?
```
default_branch = ''
cd ('.') {
}
```

</blockquote></details>

So weird, let's not dig too much

**Review by emilieguth — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/151)* status: LGTM missing from one of: zozoens31

___
*[bin/git-submit, line 24 at r3](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/151#-MW4_1uH4Fyuz2MxKfQg:-MW4qyd6C51lM4fGOL72:b-896fix) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/33267cc031b15764f3f87ff8dd3de2e2add667a3/bin/git-submit#L24)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

Please add a blank between `#` and `U`
</blockquote></details>

Done.
___
*[git-custom-commands-test/features/git-submit.feature, line 18 at r3](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/151#-MW4_9Nw8nKc-PBgY8sP:-MW4vgS-B2yiOEIUZsVx:b-896fix) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/33267cc031b15764f3f87ff8dd3de2e2add667a3/git-custom-commands-test/features/git-submit.feature#L18)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

keep "main" here and below
</blockquote></details>

Done.
___
*[git-custom-commands-test/features/steps.rb, line 17 at r3](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/151#-MW4_KTh2clFV-x-H9yn:-MW4vjON7xAmz9PfYxAx:boc3yhr) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/33267cc031b15764f3f87ff8dd3de2e2add667a3/git-custom-commands-test/features/steps.rb#L17)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

Why?
</blockquote></details>

Done. (deleted)

**Review by pcorpet — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/151)* status: LGTM missing from one of: zozoens31, Unresolved discussions (git-custom-commands-test/features/git-submit.feature:r4 line 84)

___
*[git-custom-commands-test/features/git-submit.feature, line 84 at r4](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/151#-MWBlh67Ep0_9YMG5Gjw:-MWBlh67Ep0_9YMG5Gjx:b-b6hxb6) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/8c696c45b2192d07f6e3f80b42669ea986b65837/git-custom-commands-test/features/git-submit.feature#L84)):*
> ```Gherkin
> 
>   Scenario: Change default branch name
>     Given a dummy git repo in "origin"
> ```

Please update this origin repo to use `master` as its HEAD branch.
___
*[git-custom-commands-test/features/git-submit.feature, line 86 at r4](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/151#-MWBlm4uBGtHgQGuCsyO:-MWBlm4uBGtHgQGuCsyP:b-of4dzn) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/8c696c45b2192d07f6e3f80b42669ea986b65837/git-custom-commands-test/features/git-submit.feature#L86)):*
> ```Gherkin
>     Given a dummy git repo in "origin"
>     And I am in a "work" git repo cloned from "origin"
>     And I should be on "main" git branch
> ```

You should be on master
___
*[git-custom-commands-test/features/git-submit.feature, line 88 at r4](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/151#-MWBlnx89NZOv0I46vN2:-MWBlnx89NZOv0I46vN3:b9wmyzb) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/8c696c45b2192d07f6e3f80b42669ea986b65837/git-custom-commands-test/features/git-submit.feature#L88)):*
> ```Gherkin
>     And I should be on "main" git branch
>     And I switch default branch to "master"
>     And I should be on "master" git branch
> ```

Please try a `git submit` that should update master (and not main properly).
___
*[git-custom-commands-test/features/steps.rb, line 66 at r4](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/151#-MWBlz35B8fVn64Ik2MO:-MWBlz35B8fVn64Ik2MP:b-g1f46e) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/8c696c45b2192d07f6e3f80b42669ea986b65837/git-custom-commands-test/features/steps.rb#L66)):*
> ```Ruby
> end
> 
> Given(/^I switch default branch to "([^"]+)"$/) do |name|
> ```

Actually you're switching the current branch to ...

**Review by pcorpet — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/151)* status: LGTM missing from one of: zozoens31, Unresolved discussions (git-custom-commands-test/features/steps.rb:r4 line 66)

___
*[git-custom-commands-test/features/git-submit.feature, line 87 at r4](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/151#-MWy2edt6vg5qrCPucWz:-MWy2edt6vg5qrCPucX-:bkz8k9b) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/8c696c45b2192d07f6e3f80b42669ea986b65837/git-custom-commands-test/features/git-submit.feature#L87)):*
> ```Gherkin
>     And I am in a "work" git repo cloned from "origin"
>     And I should be on "main" git branch
>     And I switch default branch to "master"
> ```

I think you should witch the default branch in origin, not in work.
___
*[git-custom-commands-test/features/git-submit.feature, line 88 at r4](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/151#-MWy2i_1AbWO3gUqlADX:-MWy2i_1AbWO3gUqlADY:buj6huh) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/8c696c45b2192d07f6e3f80b42669ea986b65837/git-custom-commands-test/features/git-submit.feature#L88)):*
> ```Gherkin
>     And I should be on "main" git branch
>     And I switch default branch to "master"
>     And I should be on "master" git branch
> ```

Please add the git submit testing.

**Review by emilieguth — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/151)* status: LGTM missing from one of: zozoens31

___
*[git-custom-commands-test/features/git-submit.feature, line 87 at r4](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/151#-MWy2edt6vg5qrCPucWz:-MX7qTVJ0F6fWfikx3YO:b-896fix) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/8c696c45b2192d07f6e3f80b42669ea986b65837/git-custom-commands-test/features/git-submit.feature#L87)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

I think you should witch the default branch in origin, not in work.
</blockquote></details>

Done.
___
*[git-custom-commands-test/features/git-submit.feature, line 88 at r4](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/151#-MWy2i_1AbWO3gUqlADX:-MX7qSUS5LVQLwJWey1y:b-896fix) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/8c696c45b2192d07f6e3f80b42669ea986b65837/git-custom-commands-test/features/git-submit.feature#L88)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

Please add the git submit testing.
</blockquote></details>

Done.
___
*[git-custom-commands-test/features/steps.rb, line 66 at r4](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/151#-MWBlz35B8fVn64Ik2MO:-MX7qRGX4g5C1SWvo3Q8:b-896fix) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/8c696c45b2192d07f6e3f80b42669ea986b65837/git-custom-commands-test/features/steps.rb#L66)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

Actually you're switching the current branch to ...
</blockquote></details>

Done.

**Review by pcorpet — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/151#-:-MXGPC-95ETfXc-bqqdT:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
