### PR TITLE
[Tests] First test for git-review.py.

### PR DESCRIPTION
**Pull request by zozoens31**
This change is [Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/318)

### CODE REVIEW

**Comment by zozoens31** [comment]
:rocket:

**Review by pcorpet — APPROVED** [review]
:lgtm:

> Reviewed 1 of 5 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/318#-:-MkuvMMq-kLPJeR2so4C:bnfp4nl)* status: Unresolved discussions (git-custom-commands-test/features/git-review.feature:r3 line 4)

___
*[git-custom-commands-test/features/git-review.feature, line 4 at r3](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/318#-MkuvFsv9s541C440xjj:-MkuvFsv9s541C440xjk:b-rvpcix) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/dd428909f9957f9c8c83ba310a5bb233840e12fd/git-custom-commands-test/features/git-review.feature#L4)):*
> ```Gherkin
> 
>   Background:
>     # TODO(pascal): Also add tests for the default (without this env var).
> ```

I guess you have more context than I do....
___
*[git-custom-commands-test/features/git-submit.feature, line 7 at r2](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/318#-MkuvAV5ADUFF7800R4K:-MkuvAV5ADUFF7800R4L:bfhzk4b) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/97edfa169ce7181fdac394f71dae76eab39e43cb/git-custom-commands-test/features/git-submit.feature#L7)):*
> ```Gherkin
>     Given I set the environment variable "NO_GIT_SUBMIT_EXPERIMENTAL" to "1"
> 
>   Scenario: Successful submission
> ```

Do not remove all those please

**Review by zozoens31 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/318)* status: :shipit: complete! all files reviewed, 2 unresolved discussions

___
*[git-custom-commands-test/features/git-review.feature, line 4 at r3](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/318#-MkuvFsv9s541C440xjj:-MkvSkqYBI8Dj9GDvehG:b-896fix) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/dd428909f9957f9c8c83ba310a5bb233840e12fd/git-custom-commands-test/features/git-review.feature#L4)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

I guess you have more context than I do....
</blockquote></details>

Done.
___
*[git-custom-commands-test/features/git-submit.feature, line 7 at r2](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/318#-MkuvAV5ADUFF7800R4K:-MkvSlnZ-enBBF7Gvu54:b-896fix) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/97edfa169ce7181fdac394f71dae76eab39e43cb/git-custom-commands-test/features/git-submit.feature#L7)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

Do not remove all those please
</blockquote></details>

Done.

**Comment by zozoens31** [comment]
:rocket:

**Comment by zozoens31** [comment]
:rocket:

**Pull request merged**
