### PR TITLE
[Review] Add the default review feature.

### LINKED ISSUE #225: Allow review from default branch
Desired workflow:
- commit on `main`
- run `git review --submit`
This creates a review on a remote branch with auto-generated name, and clears the local main branch

### PR DESCRIPTION
**Pull request by zozoens31**
Fix #225

---
This change is [Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/252)

### CODE REVIEW

**Comment by zozoens31** [comment]
:rocket:

**Review by pcorpet — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/252)* status: LGTM missing from one of: pcorpet, Unresolved discussions (bin/git-review.py:r1 line 107)

___
*[bin/git-review.py, line 107 at r1](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/252#-MbYK0Yi-Va91VY1qF4R:-MbYK0Yj54yFic4iDTU7:b-5hnxpx) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/15673afdb484752024bf324a4f9c56576cd69b6a/bin/git-review.py#L107)):*
> ```Python
> 
> 
> def _create_default_review() -> Optional[str]:
> ```

This is not really creating a **review** but a new local branch. Please update this name and/or add a documentation so that it's clearer what it's about.
___
*[bin/git-review.py, line 109 at r1](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/252#-MbYJjXO5lPqZB_yM5nB:-MbYJjXO5lPqZB_yM5nC:b-c8r953) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/15673afdb484752024bf324a4f9c56576cd69b6a/bin/git-review.py#L109)):*
> ```Python
> def _create_default_review() -> Optional[str]:
>     _run_git(['fetch'])
>     merge_base = _run_git(['merge-base', 'HEAD', 'origin/HEAD'])
> ```

I'm not sure origin/HEAD is always properly defined. I remember Émilie doing some fancy danse to get it and finally ended up checking for main, then master if it wasn't present.
___
*[bin/git-review.py, line 114 at r1](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/252#-MbYJSOO-DsaX52wmpt4:-MbYJSOO-DsaX52wmpt5:b-ynndzp) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/15673afdb484752024bf324a4f9c56576cd69b6a/bin/git-review.py#L114)):*
> ```Python
>         return None
>     title = _run_git(['log', '-1', r'--format=%s'])
>     branch = '-'.join(
> ```

Please add a comment `# Create  a branch name from the two first words of the commit message`
___
*[bin/git-review.py, line 121 at r1](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/252#-MbYKAqg1MCBpoWp-mqS:-MbYKAqg1MCBpoWp-mqT:b-a0yjfy) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/15673afdb484752024bf324a4f9c56576cd69b6a/bin/git-review.py#L121)):*
> ```Python
>     _run_git(['reset', '--hard', merge_base])
>     _run_git(['checkout', '-'])
>     _get_head.cache_clear()
> ```

That is bold: it brings some tight coupling between those functions. Maybe add a TODO to clean this pattern.

**Comment by zozoens31** [comment]
:rocket:

**Review by zozoens31 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/252)* status: LGTM missing from one of: pcorpet

___
*[bin/git-review.py, line 107 at r1](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/252#-MbYK0Yi-Va91VY1qF4R:-Mb_yvLVBhF6WsUNIjcs:b-896fix) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/15673afdb484752024bf324a4f9c56576cd69b6a/bin/git-review.py#L107)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

This is not really creating a **review** but a new local branch. Please update this name and/or add a documentation so that it's clearer what it's about.
</blockquote></details>

Done.
___
*[bin/git-review.py, line 109 at r1](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/252#-MbYJjXO5lPqZB_yM5nB:-Mb_yvj6DAczZoOoFH1T:b-qqe4ns) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/15673afdb484752024bf324a4f9c56576cd69b6a/bin/git-review.py#L109)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

I'm not sure origin/HEAD is always properly defined. I remember Émilie doing some fancy danse to get it and finally ended up checking for main, then master if it wasn't present.
</blockquote></details>

Done. In another CL
___
*[bin/git-review.py, line 114 at r1](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/252#-MbYJSOO-DsaX52wmpt4:-Mb_yxHLE95jgnFb1sRR:b-896fix) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/15673afdb484752024bf324a4f9c56576cd69b6a/bin/git-review.py#L114)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

Please add a comment `# Create  a branch name from the two first words of the commit message`
</blockquote></details>

Done.
___
*[bin/git-review.py, line 121 at r1](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/252#-MbYKAqg1MCBpoWp-mqS:-Mb_yyAC7Dhwk-J69jbG:b-896fix) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/15673afdb484752024bf324a4f9c56576cd69b6a/bin/git-review.py#L121)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

That is bold: it brings some tight coupling between those functions. Maybe add a TODO to clean this pattern.
</blockquote></details>

Done.

**Review by pcorpet — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/252#-:-Mb_zcrs36I65Jhaww5m:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
