### PR TITLE
Implement a custom reviewable rule

### PR DESCRIPTION
**Pull request by dedan**
+@pcorpet

---
This change is [Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/36)

### CODE REVIEW

**Comment by dedan** [comment]
+@pcorpet  Hey Pascal, here finally my custom reviewable rule. Sorry, I know this PR got way too big for my taste. But it was so much trial and error over several days, did not manage to break it up.

---

Review status: 0 of 9 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/36#-:-KL6JFDeYiDZv0FRxLbu:-2083725192)*

**Comment by pcorpet** [comment]
So so cool. Thanks for doing that. It looks quite complete to me. I've added many comments on the tests, but I think you should postpone any chnage to later: it's good as it is.
:lgtm:

---

Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 17 unresolved discussions.

---

*[.gitignore, line 9 \[r1\]](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/36#-KL6aZjnA9Xtx6yd4pQe:-KL6aZjnA9Xtx6yd4pQf:1077627643) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/723cf730fb76fa3bc9cd12a0f8ecd9de2e9edf70/.gitignore#L9)):*
> ```
> 
> # Node files
> node_modules
> ```

why do we have them in our folder? they should only be created on Docker...

---

*[circle.yml, line 15 \[r1\]](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/36#-KL6bVnWvFkt9yFTbWpu:-KL6bVnWvFkt9yFTbWpv:2136963104) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/723cf730fb76fa3bc9cd12a0f8ecd9de2e9edf70/circle.yml#L15)):*
> ```YAML
>   override:
>     - docker-compose run test
>     - docker-compose run test-reviewable npm run test
> ```

This test is quite long to run because it's also building the container. I suggest we build the containers in dependencies part like we do in other repo. That way the timing of each test will be only about the testing part.

---

*[reviewable/.eslintrc.json, line 3 \[r1\]](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/36#-KL8e1dAJIco9cB3A-hm:-KL8e1dAJIco9cB3A-hn:-1280936503) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/723cf730fb76fa3bc9cd12a0f8ecd9de2e9edf70/reviewable/.eslintrc.json#L3)):*
> ```JSON
> {
>   "extends": ["eslint:recommended"],
>   // "parser": "babel-eslint",
> ```

remove

---

*[reviewable/Dockerfile, line 1 \[r1\]](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/36#-KL8dEDIwCSqqp--mi0o:-KL8dEDJkGs3n2IGrvQh:-1969559252) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/723cf730fb76fa3bc9cd12a0f8ecd9de2e9edf70/reviewable/Dockerfile#L1)):*
> ```Dockerfile
> FROM node:4-onbuild
> ```

I would add a default CMD:
`CMD npm run test`

so that running the test is only
`docker-compose run test-reviewable`

and you can always overrule it:
`docker-compose run test-reviewable npm run lint`

---

*[reviewable/lgtm_plus_resolved_discussions.js, line 2 \[r1\]](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/36#-KL8dMpbZnpsj6EmH8JA:-KL8dMpbZnpsj6EmH8JB:-1774978590) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/723cf730fb76fa3bc9cd12a0f8ecd9de2e9edf70/reviewable/lgtm_plus_resolved_discussions.js#L2)):*
> ```JavaScript
> 'use strict'
> // This code will check that the pull request has been approved
> ```

please explain that the data is given to this script as `review` object, and maybe a pointer to where it's documented.

---

*[reviewable/lgtm_plus_resolved_discussions.js, line 11 \[r1\]](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/36#-KL6c8vVcZeCpWCM5OyX:-KL6c8vW1zZs0lVIEhBC:1262264621) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/723cf730fb76fa3bc9cd12a0f8ecd9de2e9edf70/reviewable/lgtm_plus_resolved_discussions.js#L11)):*
> ```JavaScript
> const descriptions = []
> 
> // LGTM approval.
> ```

Add a TODO to check for "cancel LGTM"

---

*[reviewable/lgtm_plus_resolved_discussions.js, line 24 \[r1\]](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/36#-KL6cODfTshzFYv_HvLG:-KL6cODfTshzFYv_HvLH:2136279039) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/723cf730fb76fa3bc9cd12a0f8ecd9de2e9edf70/reviewable/lgtm_plus_resolved_discussions.js#L24)):*
> ```JavaScript
> const atLeastOneLgtm = !!_.intersection(approvals, assignees).length
> if (!atLeastOneLgtm) {
>   descriptions.push('LGTM missing!')
> ```

No need to be dramatic, please remove the "!" (same below)

---

*[reviewable/lgtm_plus_resolved_discussions.js, line 43 \[r1\]](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/36#-KL6cLwSTwOj5K_DgTFH:-KL6cLwSTwOj5K_DgTFI:1385088664) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/723cf730fb76fa3bc9cd12a0f8ecd9de2e9edf70/reviewable/lgtm_plus_resolved_discussions.js#L43)):*
> ```JavaScript
> if (!allFilesReviewed && _.some(fileBlockers, user => !user)) {
>   fileBlockers =
>     fileBlockers.concat(review.pullRequest.assignees)
> ```

keep on the same line if you can

---

*[reviewable/package.json, line 4 \[r1\]](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/36#-KL8dXbQHCMLAWdA6x8_:-KL8dXbQHCMLAWdA6x8a:-1326166121) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/723cf730fb76fa3bc9cd12a0f8ecd9de2e9edf70/reviewable/package.json#L4)):*
> ```JSON
>   "name": "reviewable",
>   "version": "1.0.0",
>   "description": "Bayes PR conditions for reviewable",
> ```

Reviewable

---

*[reviewable/package.json, line 12 \[r1\]](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/36#-KL8cDLVS-PrJStqzcoj:-KL8cDLVS-PrJStqzcok:-2029778449) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/723cf730fb76fa3bc9cd12a0f8ecd9de2e9edf70/reviewable/package.json#L12)):*
> ```JSON
>     "lint": "./node_modules/.bin/eslint . --ext js",
>     "test": "./node_modules/.bin/mocha --reporter spec",
>     "test:watch": "./node_modules/.bin/mocha --reporter spec --watch"
> ```

document this feature somewhere if you find it useful

---

*[reviewable/README.md, line 1 \[r1\]](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/36#-KL6b5hDfOONwtKuE09-:-KL6b5hDfOONwtKuE090:390396425) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/723cf730fb76fa3bc9cd12a0f8ecd9de2e9edf70/reviewable/README.md#L1)):*
> ```Markdown
> # Reviewable Configuration
> ```

Please add how I can run tests.

---

*[reviewable/test/lgtm_plus_resolved_discussions_spec.js, line 8 \[r1\]](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/36#-KL8_iks_zdfjnMbP2UX:-KL8_iks_zdfjnMbP2UY:-1781851881) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/723cf730fb76fa3bc9cd12a0f8ecd9de2e9edf70/reviewable/test/lgtm_plus_resolved_discussions_spec.js#L8)):*
> ```JavaScript
> 
> const codeToTest = fs.readFileSync('lgtm_plus_resolved_discussions.js', {encoding: 'utf8'})
> const funcToTest = new Function('_', 'review', codeToTest)
> ```

Wow, I didn't know about this feature in Javascript. I would have used `eval` which is an evil pattern. Congrats on sorting it out.

---

*[reviewable/test/lgtm_plus_resolved_discussions_spec.js, line 11 \[r1\]](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/36#-KL6cw59m6imtPsJwnHu:-KL6cw59m6imtPsJwnHv:-498227545) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/723cf730fb76fa3bc9cd12a0f8ecd9de2e9edf70/reviewable/test/lgtm_plus_resolved_discussions_spec.js#L11)):*
> ```JavaScript
> 
> 
> const template = {
> ```

Explain why you are creating that: I guess this is to easily setup tests with all default values.

---

*[reviewable/test/lgtm_plus_resolved_discussions_spec.js, line 30 \[r1\]](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/36#-KL8_yyJVGdsugerGYBK:-KL8_yyJVGdsugerGYBL:1119750418) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/723cf730fb76fa3bc9cd12a0f8ecd9de2e9edf70/reviewable/test/lgtm_plus_resolved_discussions_spec.js#L30)):*
> ```JavaScript
>   })
> 
>   it('should not be complete without LGTM of one assignee', function() {
> ```

You describe your tests as specs, but they actually look like scenarios to me. I'm kind of surprised because this checks many different things. I think you are unit testing a function so each test should actually call the function only once with a set of parameters and describe what it does.

I suggest you add a TODO to split it in smaller unit tests rather of a scenario.

---

*[reviewable/test/lgtm_plus_resolved_discussions_spec.js, line 32 \[r1\]](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/36#-KL8adtamwWG8yfmj88b:-KL8adtamwWG8yfmj88c:-56138871) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/723cf730fb76fa3bc9cd12a0f8ecd9de2e9edf70/reviewable/test/lgtm_plus_resolved_discussions_spec.js#L32)):*
> ```JavaScript
>   it('should not be complete without LGTM of one assignee', function() {
>     review.pullRequest.assignees.push({username: 'pcorpet'})
>     let res = funcToTest(_, review)
> ```

Just to make my point clearer:

The following function would pass your test without doing anything near what you want it to do:

```
funcToTest = function(_, review) {
  review.success = (review.success || 0) + 1
  return {completed: review.success >= 4}
}
```

My point is not that you should make sure your tests only work for the function you have, but that independent unittests are stronger.

---

*[reviewable/test/lgtm_plus_resolved_discussions_spec.js, line 36 \[r1\]](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/36#-KL8bz3G5AC7Rxdm7I4E:-KL8bz3G5AC7Rxdm7I4F:-138305962) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/723cf730fb76fa3bc9cd12a0f8ecd9de2e9edf70/reviewable/test/lgtm_plus_resolved_discussions_spec.js#L36)):*
> ```JavaScript
> 
>     review.sentiments.push({
>       'username': 'dedan',
> ```

do you need quotes around `username`, you don't seem to use this syntax above.

---

*[reviewable/test/lgtm_plus_resolved_discussions_spec.js, line 68 \[r1\]](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/36#-KL8c3DdALp75NxYolYx:-KL8c3DdALp75NxYolYy:207101655) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/723cf730fb76fa3bc9cd12a0f8ecd9de2e9edf70/reviewable/test/lgtm_plus_resolved_discussions_spec.js#L68)):*
> ```JavaScript
>   it('mark discussions as resolved when the author is resolved', function() {
>     review.discussions.push({
>       'numMessages': 2,
> ```

same here, please remove the quotes (or explain them to me).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/36#-:-KL8cTagT1-0455Mjwav:-1291919852)*

**Comment by dedan** [comment]
thank you very much for the constructive feedback.

---

Review status: 2 of 10 files reviewed at latest revision, 16 unresolved discussions, some commit checks failed.

---

*[.gitignore, line 9 \[r1\]](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/36#-KL6aZjnA9Xtx6yd4pQe:-KLFhVUEvq-fGKEOU75C:458379055) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/723cf730fb76fa3bc9cd12a0f8ecd9de2e9edf70/.gitignore#L9)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary>
> why do we have them in our folder? they should only be created on Docker...
</details>
Done. Was a leftover from when I ran it without docker

---

*[circle.yml, line 15 \[r1\]](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/36#-KL6bVnWvFkt9yFTbWpu:-KLFhz2SmQ8cGoiFRMNR:-499146009) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/723cf730fb76fa3bc9cd12a0f8ecd9de2e9edf70/circle.yml#L15)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary>
> This test is quite long to run because it's also building the container. I suggest we build the containers in dependencies part like we do in other repo. That way the timing of each test will be only about the testing part.
</details>
Done.

---

*[reviewable/.eslintrc.json, line 3 \[r1\]](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/36#-KL8e1dAJIco9cB3A-hm:-KLFi65w823n-Ull0oXS:-499146009) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/723cf730fb76fa3bc9cd12a0f8ecd9de2e9edf70/reviewable/.eslintrc.json#L3)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary>
> remove
</details>
Done.

---

*[reviewable/Dockerfile, line 1 \[r1\]](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/36#-KL8dEDIwCSqqp--mi0o:-KLFiTfFq749j0jCi101:-499146009) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/723cf730fb76fa3bc9cd12a0f8ecd9de2e9edf70/reviewable/Dockerfile#L1)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary>
> I would add a default CMD:
> `CMD npm run test`
> 
> so that running the test is only
> `docker-compose run test-reviewable`
> 
> and you can always overrule it:
> `docker-compose run test-reviewable npm run lint`
</details>
Done.

---

*[reviewable/lgtm_plus_resolved_discussions.js, line 2 \[r1\]](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/36#-KL8dMpbZnpsj6EmH8JA:-KLFirXkKr6pO8IGtG5K:-499146009) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/723cf730fb76fa3bc9cd12a0f8ecd9de2e9edf70/reviewable/lgtm_plus_resolved_discussions.js#L2)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary>
> please explain that the data is given to this script as `review` object, and maybe a pointer to where it's documented.
</details>
Done.

---

*[reviewable/lgtm_plus_resolved_discussions.js, line 11 \[r1\]](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/36#-KL6c8vVcZeCpWCM5OyX:-KLFiw4TFHxRYA99WqM5:-499146009) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/723cf730fb76fa3bc9cd12a0f8ecd9de2e9edf70/reviewable/lgtm_plus_resolved_discussions.js#L11)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary>
> Add a TODO to check for "cancel LGTM"
</details>
Done.

---

*[reviewable/lgtm_plus_resolved_discussions.js, line 24 \[r1\]](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/36#-KL6cODfTshzFYv_HvLG:-KLFj4CdXEsfMThHZ4Rs:-1129588816) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/723cf730fb76fa3bc9cd12a0f8ecd9de2e9edf70/reviewable/lgtm_plus_resolved_discussions.js#L24)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary>
> No need to be dramatic, please remove the "!" (same below)
</details>
Done. But I love drama! ;-)

---

*[reviewable/lgtm_plus_resolved_discussions.js, line 43 \[r1\]](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/36#-KL6cLwSTwOj5K_DgTFH:-KLFjCsgSTEqJEFpAOzs:-499146009) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/723cf730fb76fa3bc9cd12a0f8ecd9de2e9edf70/reviewable/lgtm_plus_resolved_discussions.js#L43)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary>
> keep on the same line if you can
</details>
Done.

---

*[reviewable/package.json, line 4 \[r1\]](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/36#-KL8dXbQHCMLAWdA6x8_:-KLFjGJGCpV6Rz3vW_K8:-499146009) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/723cf730fb76fa3bc9cd12a0f8ecd9de2e9edf70/reviewable/package.json#L4)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary>
> Reviewable
</details>
Done.

---

*[reviewable/package.json, line 12 \[r1\]](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/36#-KL8cDLVS-PrJStqzcoj:-KLFjpexszVC6kFNd_EI:-499146009) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/723cf730fb76fa3bc9cd12a0f8ecd9de2e9edf70/reviewable/package.json#L12)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary>
> document this feature somewhere if you find it useful
</details>
Done.

---

*[reviewable/README.md, line 1 \[r1\]](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/36#-KL6b5hDfOONwtKuE09-:-KLFjt7QE1AlN5vBEIck:-499146009) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/723cf730fb76fa3bc9cd12a0f8ecd9de2e9edf70/reviewable/README.md#L1)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary>
> Please add how I can run tests.
</details>
Done.

---

*[reviewable/test/lgtm_plus_resolved_discussions_spec.js, line 11 \[r1\]](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/36#-KL6cw59m6imtPsJwnHu:-KLFkAL6dL6RcYF3C5Uw:-499146009) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/723cf730fb76fa3bc9cd12a0f8ecd9de2e9edf70/reviewable/test/lgtm_plus_resolved_discussions_spec.js#L11)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary>
> Explain why you are creating that: I guess this is to easily setup tests with all default values.
</details>
Done.

---

*[reviewable/test/lgtm_plus_resolved_discussions_spec.js, line 30 \[r1\]](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/36#-KL8_yyJVGdsugerGYBK:-KLFkGpIZj-VPgYVjBjE:850660219) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/723cf730fb76fa3bc9cd12a0f8ecd9de2e9edf70/reviewable/test/lgtm_plus_resolved_discussions_spec.js#L30)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary>
> You describe your tests as specs, but they actually look like scenarios to me. I'm kind of surprised because this checks many different things. I think you are unit testing a function so each test should actually call the function only once with a set of parameters and describe what it does.
> 
> I suggest you add a TODO to split it in smaller unit tests rather of a scenario.
</details>
Done. Thank you for that advice. I still never know on which level to test my stuff.

---

*[reviewable/test/lgtm_plus_resolved_discussions_spec.js, line 36 \[r1\]](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/36#-KL8bz3G5AC7Rxdm7I4E:-KLFkjLvhguixf0mEZyh:-499146009) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/723cf730fb76fa3bc9cd12a0f8ecd9de2e9edf70/reviewable/test/lgtm_plus_resolved_discussions_spec.js#L36)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary>
> do you need quotes around `username`, you don't seem to use this syntax above.
</details>
Done.

---

*[reviewable/test/lgtm_plus_resolved_discussions_spec.js, line 68 \[r1\]](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/36#-KL8c3DdALp75NxYolYx:-KLFkjpxHKxwp74a51Je:-499146009) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/723cf730fb76fa3bc9cd12a0f8ecd9de2e9edf70/reviewable/test/lgtm_plus_resolved_discussions_spec.js#L68)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary>
> same here, please remove the quotes (or explain them to me).
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/36#-:-KLFl0SdPjSOI1YfWf-L:1667859061)*

**Comment by pcorpet** [comment]
:lgtm:

---

Reviewed 8 of 8 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[circle.yml, line 10 \[r2\]](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/36#-KLFpW-T4_U7QmzP3G4m:-KLFpW-T4_U7QmzP3G4n:410652874) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/89106d977a993a6f6ae2e4dd52867557efe36b21/circle.yml#L10)):*
> ```YAML
> dependencies:
>   post:
>     - sudo pip install --upgrade docker-compose==1.6.2
> ```

It feels weird to upgrade docker-compose, after (`post`) running it. Either move this one to `pre` or also run the `docker-compose build` in the post.

---

*[reviewable/Dockerfile, line 1 \[r1\]](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/36#-KL8dEDIwCSqqp--mi0o:-KLFpiLm-Yl6O4_U_Qd_:1057984269) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/723cf730fb76fa3bc9cd12a0f8ecd9de2e9edf70/reviewable/Dockerfile#L1)):*
<details><summary><i>Previously, dedan (Stephan Gabler) wrote…</i></summary>
> Done.
</details>
I recommend adding the CMD before the COPY: this is one less step to rebuild when package.json changes.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/36#-:-KLFqBnDJGocE86aLhf9:1417088721)*

**Comment by dedan** [comment]
Review status: 9 of 10 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[reviewable/Dockerfile, line 1 \[r1\]](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/36#-KL8dEDIwCSqqp--mi0o:-KLGCY0kg87XAO8Vh3sz:1072388904) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/723cf730fb76fa3bc9cd12a0f8ecd9de2e9edf70/reviewable/Dockerfile#L1)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary>
> I recommend adding the CMD before the COPY: this is one less step to rebuild when package.json changes.
</details>
Done. Cool, thanks. For some reason I thought the CMD one has to be the last

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/36)*

**Comment by dedan** [comment]
Review status: 8 of 10 files reviewed at latest revision, 2 unresolved discussions.

---

*[circle.yml, line 10 \[r2\]](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/36#-KLFpW-T4_U7QmzP3G4m:-KLGdxizX9ZRaHJJ2RWp:-499146009) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/89106d977a993a6f6ae2e4dd52867557efe36b21/circle.yml#L10)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary>
> It feels weird to upgrade docker-compose, after (`post`) running it. Either move this one to `pre` or also run the `docker-compose build` in the post.
</details>
Done.

---

*[reviewable/Dockerfile, line 1 \[r1\]](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/36#-KL8dEDIwCSqqp--mi0o:-KLGdx9Sb_TIyMjYzCLE:-499146009) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/723cf730fb76fa3bc9cd12a0f8ecd9de2e9edf70/reviewable/Dockerfile#L1)):*
<details><summary><i>Previously, dedan (Stephan Gabler) wrote…</i></summary>
> Done. Cool, thanks. For some reason I thought the CMD one has to be the last
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/36)*

**Pull request merged**
