### PR TITLE
[Review] Add reviewers on 'git review -f'.

### PR DESCRIPTION
**Pull request by zozoens31**
This change is [Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/250)

### CODE REVIEW

**Comment by zozoens31** [comment]
:rocket:

**Review by pcorpet — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/250)* status: LGTM missing from one of: pcorpet, Unresolved discussions (bin/git-review.py:r1 line 241)

___
*[bin/git-review.py, line 241 at r1](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/250#-MbXugQjBUpZUYpGN9dZ:-MbXugQjBUpZUYpGN9d_:b1l84ou) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/85f305daa35519e6976af231a88988f9e1125446/bin/git-review.py#L241)):*
> ```Python
>             if not users:
>                 return
>             merge_request = next(
> ```

It seems that this could be used to implement get_review_number. I suggest that you at least move it in a helper function and add a TODO to use this helper function in those other methods.
___
*[bin/git-review.py, line 351 at r1](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/250#-MbXu1Cr-g0LjL4FN8Dy:-MbXu1Cr-g0LjL4FN8Dz:b-fk0r6r) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/85f305daa35519e6976af231a88988f9e1125446/bin/git-review.py#L351)):*
> ```Python
>         raise _ScriptError('All code on this branch has already been submitted.')
>     _push(refs, is_forced)
>     _request_review(refs, reviewers, create=not is_forced)
> ```

I don't think I like the logic that "creating is when you're not forcing it". The semantic of forcing, is to bypass any error (especially on git push). Maybe we should have a proper semantic of what we want to do and I'm almost sure that `git review` always want to create when **the PR does not exist yet**

**Comment by zozoens31** [comment]
:rocket:

**Review by zozoens31 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/250)* status: LGTM missing from one of: emilieguth,pcorpet, Unresolved discussions (bin/git-review.py:r1 line 351)

___
*[bin/git-review.py, line 241 at r1](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/250#-MbXugQjBUpZUYpGN9dZ:-Mba-OMW3PC0jEU7A109:b-896fix) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/85f305daa35519e6976af231a88988f9e1125446/bin/git-review.py#L241)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

It seems that this could be used to implement get_review_number. I suggest that you at least move it in a helper function and add a TODO to use this helper function in those other methods.
</blockquote></details>

Done.
___
*[bin/git-review.py, line 351 at r1](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/250#-MbXu1Cr-g0LjL4FN8Dy:-Mba-lwc5FJYojXHc81y:b-f4jv8o) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/85f305daa35519e6976af231a88988f9e1125446/bin/git-review.py#L351)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

I don't think I like the logic that "creating is when you're not forcing it". The semantic of forcing, is to bypass any error (especially on git push). Maybe we should have a proper semantic of what we want to do and I'm almost sure that `git review` always want to create when **the PR does not exist yet**
</blockquote></details>

Good point. I'll implement that behaviour in another CL, and put this one on top of it.

**Review by pcorpet — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/250#-:-MbaBHQG62ZWkDfF03az:bnfp4nl)* status: Unresolved discussions (bin/git-review.py:r1 line 351)

*[a discussion](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/250#-MbaBKCk04euwy_eWvrr:-MbaBKCl7aeOYZd450Cy:b-jymer7) (no related file):*
Please update the commit message as you're not doing it on `-f`

---

**Comment by zozoens31** [comment]
:rocket:

**Review by zozoens31 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/250)* status: :shipit: complete! 0 of 1 files reviewed, 2 unresolved discussions

*[a discussion](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/250#-MbaBKCk04euwy_eWvrr:-Mbb-dFQ0M6V-1By0Mj7:b-896fix) (no related file):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

Please update the commit message as you're not doing it on `-f`
</blockquote></details>

Done.

---
___
*[bin/git-review.py, line 351 at r1](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/250#-MbXu1Cr-g0LjL4FN8Dy:-Mbb-dwa6RBhIBTn_8rg:b-896fix) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/85f305daa35519e6976af231a88988f9e1125446/bin/git-review.py#L351)):*
<details><summary><i>Previously, zozoens31 (Cyrille Corpet) wrote…</i></summary><blockquote>

Good point. I'll implement that behaviour in another CL, and put this one on top of it.
</blockquote></details>

Done.

**Pull request merged**
