### PR TITLE
[Review] Automatically assign a reviewer.

### PR DESCRIPTION
**Pull request by zozoens31**
This change is [Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/265)

### CODE REVIEW

**Comment by zozoens31** [comment]
:rocket:

**Comment by zozoens31** [comment]
:rocket:

**Review by emilieguth — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/265#-:-Mbjt3VD-kr8GvixAGJz:bnfp4nl)* status: :shipit: complete! 0 of 1 files reviewed, all discussions resolved

**Comment by zozoens31** [comment]
:rocket:

**Pull request merged**
