### PR TITLE
[Python] Use python for git review script.

### PR DESCRIPTION
**Pull request by zozoens31**
This change is [Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/213)

### CODE REVIEW

**Review by pcorpet — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/213)* status: LGTM missing from one of: pcorpet, Unresolved discussions (bin/git-review.py:r1 line 8)

___
*[bin/git-review.py, line 8 at r1](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/213#-Mb0hPDX607Kv_DkurjD:-Mb0hPDX607Kv_DkurjE:b-7xdheq) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/ba296ca81e59b5d4d814aa73ee74171373ba26df/bin/git-review.py#L8)):*
> ```Python
> with the specified reviewers (if any).
> 
> PYTHON_ARGCOMPLETE_OK
> ```

This doesn't work, please remove and add a TODO to enable it.
___
*[bin/git-review.py, line 28 at r1](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/213#-Mb0jggW6iKf0l6sggWf:-Mb0jggW6iKf0l6sggWg:bslvgex) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/ba296ca81e59b5d4d814aa73ee74171373ba26df/bin/git-review.py#L28)):*
> ```Python
>     # This is not needed when pushing to a Github repo.
>     gitlab = None
> import unidecode
> ```

Make sure you add this dependency somewhere (probably in install.sh)
___
*[bin/git-review.py, line 35 at r1](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/213#-Mb0j1Y1-U8szs-K6yLP:-Mb0j1Y21ObK82a7T9vH:b-hj4t2s) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/ba296ca81e59b5d4d814aa73ee74171373ba26df/bin/git-review.py#L35)):*
> ```Python
> 
> 
> _REMOTE_REPO = 'origin'
> ```

Please document
___
*[bin/git-review.py, line 36 at r1](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/213#-Mb0jEAr-fBvN621ppz-:-Mb0jEAr-fBvN621ppz0:b-de1o74) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/ba296ca81e59b5d4d814aa73ee74171373ba26df/bin/git-review.py#L36)):*
> ```Python
> 
> _REMOTE_REPO = 'origin'
> _DEFAULT_USERNAME = _run_git(['config', 'user.email']).split('@')[0]
> ```

Run this in `main` instead (this is no really a module config)
___
*[bin/git-review.py, line 39 at r1](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/213#-Mb0j9RmAe9JNepIh8ur:-Mb0j9RmAe9JNepIh8us:b-2cci3c) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/ba296ca81e59b5d4d814aa73ee74171373ba26df/bin/git-review.py#L39)):*
> ```Python
> 
> 
> def _has_git_diff(base: str) -> bool:
> ```

Keep this one closer to _run_git please.
___
*[bin/git-review.py, line 43 at r1](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/213#-Mb0jJ3X6OFNQWg43KMV:-Mb0jJ3X6OFNQWg43KMW:byhs0xb) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/ba296ca81e59b5d4d814aa73ee74171373ba26df/bin/git-review.py#L43)):*
> ```Python
> 
> 
> class References(typing.NamedTuple):
> ```

Make this class protected (prefix with _)
___
*[bin/git-review.py, line 53 at r1](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/213#-Mb0jNNm5czAWjnkvD8Y:-Mb0jNNn5GxmbRSV9F3h:bl1sr92) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/ba296ca81e59b5d4d814aa73ee74171373ba26df/bin/git-review.py#L53)):*
> ```Python
> 
> 
> def _get_git_branches(username: str, base: Optional[str]) -> References:
> ```

Please document (same for all functions here).
___
*[bin/git-submit, line 156 at r1](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/213#-Mb0hKxY8yHrWV5HAsbv:-Mb0hKxY8yHrWV5HAsbw:b-9fbjsv) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/ba296ca81e59b5d4d814aa73ee74171373ba26df/bin/git-submit#L156)):*
> ```
>       repository(name: "{repo}", owner: "{owner}") {
>         deleteBranchOnMerge
>         viewerCanAdminister
> ```

Please move to another CL.

**Review by zozoens31 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/213)* status: LGTM missing from one of: pcorpet

___
*[bin/git-review.py, line 8 at r1](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/213#-Mb0hPDX607Kv_DkurjD:-Mb0r1UuDsB9Q5OxPnHQ:b-896fix) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/ba296ca81e59b5d4d814aa73ee74171373ba26df/bin/git-review.py#L8)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

This doesn't work, please remove and add a TODO to enable it.
</blockquote></details>

Done.
___
*[bin/git-review.py, line 28 at r1](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/213#-Mb0jggW6iKf0l6sggWf:-Mb0rBlo8Qgq82291hoi:b-896fix) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/ba296ca81e59b5d4d814aa73ee74171373ba26df/bin/git-review.py#L28)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

Make sure you add this dependency somewhere (probably in install.sh)
</blockquote></details>

Done.
___
*[bin/git-review.py, line 35 at r1](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/213#-Mb0j1Y1-U8szs-K6yLP:-Mb0rPpi3NanNh9xEjPL:b-896fix) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/ba296ca81e59b5d4d814aa73ee74171373ba26df/bin/git-review.py#L35)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

Please document
</blockquote></details>

Done.
___
*[bin/git-review.py, line 36 at r1](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/213#-Mb0jEAr-fBvN621ppz-:-Mb0siZy144y4zflUIu_:b-896fix) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/ba296ca81e59b5d4d814aa73ee74171373ba26df/bin/git-review.py#L36)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

Run this in `main` instead (this is no really a module config)
</blockquote></details>

Done.
___
*[bin/git-review.py, line 39 at r1](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/213#-Mb0j9RmAe9JNepIh8ur:-Mb0sqS14OyrQPlomFwn:b-896fix) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/ba296ca81e59b5d4d814aa73ee74171373ba26df/bin/git-review.py#L39)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

Keep this one closer to _run_git please.
</blockquote></details>

Done.
___
*[bin/git-review.py, line 43 at r1](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/213#-Mb0jJ3X6OFNQWg43KMV:-Mb0sr5qBV_DjPAucKaI:b-896fix) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/ba296ca81e59b5d4d814aa73ee74171373ba26df/bin/git-review.py#L43)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

Make this class protected (prefix with _)
</blockquote></details>

Done.
___
*[bin/git-review.py, line 53 at r1](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/213#-Mb0jNNm5czAWjnkvD8Y:-Mb0uV8z4jyouVdKAjJG:b-896fix) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/ba296ca81e59b5d4d814aa73ee74171373ba26df/bin/git-review.py#L53)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

Please document (same for all functions here).
</blockquote></details>

Done.
___
*[bin/git-submit, line 156 at r1](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/213#-Mb0hKxY8yHrWV5HAsbv:-Mb0ukSw0YKqDH-coMaX:b-896fix) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/ba296ca81e59b5d4d814aa73ee74171373ba26df/bin/git-submit#L156)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

Please move to another CL.
</blockquote></details>

Done.

**Review by pcorpet — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/213#-:-Mb1lvG69oVG2kZmAnlv:bnfp4nl)* status: Unresolved discussions (bin/git-review.py:r2 line 38)

___
*[bin/git-review.py, line 38 at r2](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/213#-Mb1jQLvEk2bMBEpqT14:-Mb1jQLvEk2bMBEpqT15:bly3w6c) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/5e00a5508abb9541274f66d5ed5ef8f892feb2ca/bin/git-review.py#L38)):*
> ```Python
>     """Simple structure containing all needed branch references."""
> 
>     # Default branch no the remote repository.
> ```

no => on
___
*[bin/git-review.py, line 44 at r2](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/213#-Mb1j_UrBTebMkG7plCu:-Mb1j_UrBTebMkG7plCv:b-ixer30) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/5e00a5508abb9541274f66d5ed5ef8f892feb2ca/bin/git-review.py#L44)):*
> ```Python
>     # Remote name for the reviewed branch.
>     remote: str
>     # Branch where the changes should be merged into.
> ```

Remove branch onto which the changes should be merged.
___
*[bin/git-review.py, line 95 at r2](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/213#-Mb1l0n-21oveXzQ1wHW:-Mb1l0n-21oveXzQ1wHX:b5jp0yd) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/5e00a5508abb9541274f66d5ed5ef8f892feb2ca/bin/git-review.py#L95)):*
> ```Python
> 
> 
> def _push(refs, is_forced: bool) -> None:
> ```

Please type `refs`
___
*[bin/git-review.py, line 131 at r2](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/213#-Mb1lDjo5Ww9o4Ixm-5n:-Mb1lDjo5Ww9o4Ixm-5o:betd07k) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/5e00a5508abb9541274f66d5ed5ef8f892feb2ca/bin/git-review.py#L131)):*
> ```Python
>     message = _make_pr_message(refs, reviewers)
>     if 'gitlab.com' in remote_url:
>         _request_mr(remote_url, message, refs, reviewers)
> ```

Please name the functions explicitly with gitlab and github.
___
*[bin/git-review.py, line 139 at r2](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/213#-Mb1l4-6-46pLw7pkW-g:-Mb1l4-6-46pLw7pkW-h:bpdniec) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/5e00a5508abb9541274f66d5ed5ef8f892feb2ca/bin/git-review.py#L139)):*
> ```Python
> 
> 
> def _request_mr(remote_url: str, message: str, refs: _References, reviewers: Optional[str]) -> None:
> ```

Too many chars, please break.
___
*[bin/git-review.py, line 145 at r2](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/213#-Mb1lNP-7DLq74aaXtzL:-Mb1lNP-7DLq74aaXtzM:b-w9gmk7) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/5e00a5508abb9541274f66d5ed5ef8f892feb2ca/bin/git-review.py#L145)):*
> ```Python
>         raise ValueError(
>             'gitlab tool is not installed, please install it:\n'
>             # TODO(cyrille): Switch to main, once this repo has switched.
> ```

Please use HEAD and be done with it.
___
*[bin/git-review.py, line 148 at r2](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/213#-Mb1lR9B98RgvQpTUdg0:-Mb1lR9B98RgvQpTUdg1:b-495n2s) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/5e00a5508abb9541274f66d5ed5ef8f892feb2ca/bin/git-review.py#L148)):*
> ```Python
>             '  https://github.com/bayesimpact/bayes-developer-setup/blob/master/gitlab-cli.md')
>     client = gitlab.Gitlab.from_config()
>     project_name = remote_url[len('git@gitlab.com:'):-len('.git')]
> ```

Make sure it starts with git@gitlab.com: I guess you can have https remote URLs as well.
___
*[bin/git-review.py, line 190 at r2](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/213#-Mb1lh464pGhbkZkf8ey:-Mb1lh464pGhbkZkf8ez:b-4l9si8) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/5e00a5508abb9541274f66d5ed5ef8f892feb2ca/bin/git-review.py#L190)):*
> ```Python
>     merge_base = _run_git(['merge-base', 'HEAD', f'{_REMOTE_REPO}/{refs.base}'])
>     if not _has_git_diff(merge_base):
>         raise ValueError('All code on this branch has already been submitted')
> ```

if merge_base is no `main` then the message here should be `has already been sent for review`. Please add a TODO.

**Review by zozoens31 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/213)* status: :shipit: complete! all files reviewed, 8 unresolved discussions

___
*[bin/git-review.py, line 38 at r2](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/213#-Mb1jQLvEk2bMBEpqT14:-Mb1mQF25r1bhroFrjfi:b-896fix) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/5e00a5508abb9541274f66d5ed5ef8f892feb2ca/bin/git-review.py#L38)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

no => on
</blockquote></details>

Done.
___
*[bin/git-review.py, line 44 at r2](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/213#-Mb1j_UrBTebMkG7plCu:-Mb1mX0V9gXUe41e5t1I:b-896fix) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/5e00a5508abb9541274f66d5ed5ef8f892feb2ca/bin/git-review.py#L44)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

Remove branch onto which the changes should be merged.
</blockquote></details>

Done.
___
*[bin/git-review.py, line 95 at r2](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/213#-Mb1l0n-21oveXzQ1wHW:-Mb1m_PG19ahBu7wLKZl:b-896fix) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/5e00a5508abb9541274f66d5ed5ef8f892feb2ca/bin/git-review.py#L95)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

Please type `refs`
</blockquote></details>

Done.
___
*[bin/git-review.py, line 131 at r2](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/213#-Mb1lDjo5Ww9o4Ixm-5n:-Mb1mgx0Afv1EI-qYwXw:b-896fix) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/5e00a5508abb9541274f66d5ed5ef8f892feb2ca/bin/git-review.py#L131)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

Please name the functions explicitly with gitlab and github.
</blockquote></details>

Done.
___
*[bin/git-review.py, line 139 at r2](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/213#-Mb1l4-6-46pLw7pkW-g:-Mb1mkaBCYLGv7CyIu3q:b-896fix) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/5e00a5508abb9541274f66d5ed5ef8f892feb2ca/bin/git-review.py#L139)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

Too many chars, please break.
</blockquote></details>

Done.
___
*[bin/git-review.py, line 145 at r2](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/213#-Mb1lNP-7DLq74aaXtzL:-Mb1mmEoDaihfhGkuGGd:b-896fix) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/5e00a5508abb9541274f66d5ed5ef8f892feb2ca/bin/git-review.py#L145)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

Please use HEAD and be done with it.
</blockquote></details>

Done.
___
*[bin/git-review.py, line 148 at r2](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/213#-Mb1lR9B98RgvQpTUdg0:-Mb1nrJ44NFs8kmUd78w:b-896fix) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/5e00a5508abb9541274f66d5ed5ef8f892feb2ca/bin/git-review.py#L148)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

Make sure it starts with git@gitlab.com: I guess you can have https remote URLs as well.
</blockquote></details>

Done.
___
*[bin/git-review.py, line 190 at r2](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/213#-Mb1lh464pGhbkZkf8ey:-Mb1o-Hd7nWafZf3VOwN:b-896fix) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/5e00a5508abb9541274f66d5ed5ef8f892feb2ca/bin/git-review.py#L190)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

if merge_base is no `main` then the message here should be `has already been sent for review`. Please add a TODO.
</blockquote></details>

Done.

**Comment by zozoens31** [comment]
:rocket:

**Pull request merged**
