### PR TITLE
[Submit] Allow to recreate a deleted branch from origin.

### PR DESCRIPTION
**Pull request by zozoens31**
This change is [Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/200)

### CODE REVIEW

**Review by pcorpet — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/200)* status: LGTM missing from one of: pcorpet, Unresolved discussions (bin/git-submit:r1 line 5)

___
*[bin/git-submit, line 5 at r1](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/200#-Ma8QHTM1BufVwzAqyac:-Ma8QHTM1BufVwzAqyad:b5wmi97) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/8a0e5d1c4c7d70fbcbb1c69bd19a5a8bf5f242f1/bin/git-submit#L5)):*
> ```
> # A git custom command to submit a reviewed branch.
> # Usage:
> #   git submit [<branch>]
> ```

Please update or create a man page and add a reference to this man page here.
___
*[bin/git-submit, line 19 at r1](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/200#-Ma8Q4y6C2lbJgJQep-M:-Ma8Q4y6C2lbJgJQep-N:b-yrbptt) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/8a0e5d1c4c7d70fbcbb1c69bd19a5a8bf5f242f1/bin/git-submit#L19)):*
> ```
> source "$(dirname $0)/echo_with_colors.sh"
> 
> # Parse the command line arguments.
> ```

Please do this change in another CL first
___
*[bin/git-submit, line 37 at r1](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/200#-Ma8QAsO9gMh8wsRZXeP:-Ma8QAsO9gMh8wsRZXeQ:b9y26e5) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/8a0e5d1c4c7d70fbcbb1c69bd19a5a8bf5f242f1/bin/git-submit#L37)):*
> ```
>     ;;
>     -a|--abort)
>     readonly ABORT_SUBMIT="$1"
> ```

It seems that this is the feature that you're adding, although it doesn't match the commit message.
___
*[bin/git-submit, line 42 at r1](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/200#-Ma8Pyej916FyyEy3Yro:-Ma8Pyej916FyyEy3Yrp:b-sld3rs) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/8a0e5d1c4c7d70fbcbb1c69bd19a5a8bf5f242f1/bin/git-submit#L42)):*
> ```
>     *)
>     POSITIONAL+=("$1") # save it in an array for later
>     shift # past argument
> ```

past value

**Review by zozoens31 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/200)* status: LGTM missing from one of: pcorpet

___
*[bin/git-submit, line 5 at r1](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/200#-Ma8QHTM1BufVwzAqyac:-Ma8ZsQv9-Bn8WtxVEwU:b-896fix) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/8a0e5d1c4c7d70fbcbb1c69bd19a5a8bf5f242f1/bin/git-submit#L5)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

Please update or create a man page and add a reference to this man page here.
</blockquote></details>

Done.
___
*[bin/git-submit, line 19 at r1](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/200#-Ma8Q4y6C2lbJgJQep-M:-Ma8a33oC09X3ckBn0m0:b-896fix) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/8a0e5d1c4c7d70fbcbb1c69bd19a5a8bf5f242f1/bin/git-submit#L19)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

Please do this change in another CL first
</blockquote></details>

Done.
___
*[bin/git-submit, line 37 at r1](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/200#-Ma8QAsO9gMh8wsRZXeP:-Ma8_vcx7OuuL-XDH4yJ:b-v7w5qz) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/8a0e5d1c4c7d70fbcbb1c69bd19a5a8bf5f242f1/bin/git-submit#L37)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

It seems that this is the feature that you're adding, although it doesn't match the commit message.
</blockquote></details>

See the doc about why it's called ABORT_SUBMIT, and why it's not doing that (yet)
___
*[bin/git-submit, line 42 at r1](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/200#-Ma8Pyej916FyyEy3Yro:-Ma8_r006YqkzkOXHhCo:b-896fix) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/8a0e5d1c4c7d70fbcbb1c69bd19a5a8bf5f242f1/bin/git-submit#L42)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

past value
</blockquote></details>

Done.

**Review by pcorpet — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/200#-:-MaD0rPuE9BOPK6U1Wcs:bnfp4nl)* status: Unresolved discussions (bin/git-submit:r2 line 50)

___
*[bin/git-submit, line 50 at r2](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/200#-MaD-Hwt7PuOa4PSH_T8:-MaD-Hwt7PuOa4PSH_T9:blmm2ci) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/67c74f5242afdfe2ad33d06813b81a43b1eeded3/bin/git-submit#L50)):*
> ```
> 
> # Keep in sync with git-review.
> if [ -z "$USERNAME" ] && [ -n "$ABORT_SUBMIT" ]; then
> ```

Please drop the check on ABORT_SUBMIT here, it makes the flow more confusing. If you want to do it ony for the abort case, move it closer to where it's used.
___
*[bin/git-submit, line 179 at r2](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/200#-MaD00j55bmQ7xihh7eq:-MaD00j55bmQ7xihh7er:ba9ukz1) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/67c74f5242afdfe2ad33d06813b81a43b1eeded3/bin/git-submit#L179)):*
> ```
>   git fetch
>   git branch "$BRANCH" -t "$BASE_REMOTE/$USERNAME-$BRANCH"
>   BRANCH_REMOTE="$BASE_REMOTE"
> ```

did you mean to use $BASE_REMOTE/$USERNAME-$BRANCH here?
___
*[bin/git-submit, line 194 at r2](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/200#-MaD0bUx5MvhQpm3x2TG:-MaD0bUx5MvhQpm3x2TH:b-rlmbj4) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/67c74f5242afdfe2ad33d06813b81a43b1eeded3/bin/git-submit#L194)):*
> ```
> if [ -n "$CAN_USE_HUB" ]; then
>   readonly PR_INFO="$(get_pr_info "$BRANCH_MERGE")"
>   if [ -n "$ABORT_SUBMIT" ] && [  ]; then
> ```

Please drop
___
*[man/man1/git-submit.1, line 12 at r2](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/200#-MaD0Fjz4kzeQdcuzi-R:-MaD0Fjz4kzeQdcuzi-S:b-ivmzi9) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/67c74f5242afdfe2ad33d06813b81a43b1eeded3/man/man1/git-submit.1#L12)):*
> ```Roff
> .BR \-a ", " \-\-abort\fR
> Recreate a branch from origin, without the username prefix.
> Will also cancel any auto-submission in a future release.
> ```

Please revert the doc to be closer to the flag's name.
```
Cancel any auto-submission (soon to come).
Also recreate a branch from origin , without its username prefix.
```
___
*[man/man1/git-submit.1, line 18 at r2](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/200#-MaD0XNU4GDk1aXwkyI4:-MaD0XNU4GDk1aXwkyI5:bjgbkod) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/67c74f5242afdfe2ad33d06813b81a43b1eeded3/man/man1/git-submit.1#L18)):*
> ```Roff
> .TP
> .BR \-u ", " \-\-user = USER\fR
> Set the prefix for the remote branch to USER. Default is username from the git user's email (such as in username@example.com). Only useful for
> ```

Please finalize your sentence, although I think that you use it for displaying dangling branches so I would remove the last part.

**Review by zozoens31 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/200)* status: :shipit: complete! 0 of 2 files reviewed, 6 unresolved discussions

___
*[bin/git-submit, line 50 at r2](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/200#-MaD-Hwt7PuOa4PSH_T8:-MaDlX6rD8ye6b5VHPVW:b1xrjz5) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/67c74f5242afdfe2ad33d06813b81a43b1eeded3/bin/git-submit#L50)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

Please drop the check on ABORT_SUBMIT here, it makes the flow more confusing. If you want to do it ony for the abort case, move it closer to where it's used.
</blockquote></details>

Done. I just wanted to avoid an unnecessary call to git config, but that's not too heavy
___
*[bin/git-submit, line 179 at r2](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/200#-MaD00j55bmQ7xihh7eq:-MaDlCA3AtSTDXE61cQA:b-zcoab6) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/67c74f5242afdfe2ad33d06813b81a43b1eeded3/bin/git-submit#L179)):*
No. BRANCH_REMOTE is
> The name of the remote tracked by this branch, usually "origin".
What you're talking about is `BRANCH_MERGE` which is set right below
___
*[bin/git-submit, line 194 at r2](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/200#-MaD0bUx5MvhQpm3x2TG:-MaDlPHZE0rOMtIIMEW1:b-896fix) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/67c74f5242afdfe2ad33d06813b81a43b1eeded3/bin/git-submit#L194)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

Please drop
</blockquote></details>

Done.
___
*[man/man1/git-submit.1, line 12 at r2](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/200#-MaD0Fjz4kzeQdcuzi-R:-MaDludV7VL3aH1HIjXB:b-896fix) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/67c74f5242afdfe2ad33d06813b81a43b1eeded3/man/man1/git-submit.1#L12)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

Please revert the doc to be closer to the flag's name.
```
Cancel any auto-submission (soon to come).
Also recreate a branch from origin , without its username prefix.
```
</blockquote></details>

Done.
___
*[man/man1/git-submit.1, line 18 at r2](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/200#-MaD0XNU4GDk1aXwkyI4:-MaDlyBw1pdVMwebh9hQ:b-apo7ks) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/67c74f5242afdfe2ad33d06813b81a43b1eeded3/man/man1/git-submit.1#L18)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

Please finalize your sentence, although I think that you use it for displaying dangling branches so I would remove the last part.
</blockquote></details>

Actually, I use it for `--abort`, but I want it underlined (that's the point of the .ul below).
I'll change it to a bold, this will make it more readable

**Pull request merged**
