### PR TITLE
[Clean Code] Use generic methods for git config.

### PR DESCRIPTION
**Pull request by zozoens31**
This change is [Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/285)

### CODE REVIEW

**Comment by zozoens31** [comment]
:rocket:

**Review by pcorpet — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/285#-:-McEW9Yl4FzCEGcgbPrO:bnfp4nl)* status: Unresolved discussions (bin/git-review.py:r1 line 170)

___
*[bin/git-review.py, line 170 at r1](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/285#-McEVpqUB0Uq-rm96HdU:-McEVpqUB0Uq-rm96HdV:b9asx0) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/fbd9b4bc02cb9ea430d52b418858b9f71f1f4d9b/bin/git-review.py#L170)):*
> ```Python
>         """List of reviewers, starting with the most recently used ones."""
> 
>         return self.get_config('review.recent', is_global=True).split(',')
> ```

Why do you read from global only, I think the default git config behavior (checking local first, then going to global if no local is defined) is perfect for us.
___
*[bin/git-review.py, line 579 at r1](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/285#-McEW5AQ14_6BDRoYG8z:-McEW5AQ14_6BDRoYG9-:b-8wkoy2) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/fbd9b4bc02cb9ea430d52b418858b9f71f1f4d9b/bin/git-review.py#L579)):*
> ```Python
> 
> 
> def _ask_for_email(potential: str) -> str:
> ```

Not related, please drop.

**Comment by zozoens31** [comment]
:rocket:

**Review by zozoens31 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/285)* status: :shipit: complete! 0 of 1 files reviewed, 2 unresolved discussions

___
*[bin/git-review.py, line 170 at r1](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/285#-McEVpqUB0Uq-rm96HdU:-McEX5Ym4xBQkDyGdjXC:b-cirlte) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/fbd9b4bc02cb9ea430d52b418858b9f71f1f4d9b/bin/git-review.py#L170)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

Why do you read from global only, I think the default git config behavior (checking local first, then going to global if no local is defined) is perfect for us.
</blockquote></details>

Well, that depends on where we write it... If I set it with --global, there's no point in reading locally first. Conversely, if I set it locally, there's no point in checking for the global value. And I cannot merge the two values consistently if they exist.

On the question whether we should save reviewers locally or globally, I believe the goal of the round-robin is to assign to different people every time, so it makes sense to me to use a global queue
___
*[bin/git-review.py, line 579 at r1](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/285#-McEW5AQ14_6BDRoYG8z:-McEYJscA6ftdKYilgmA:b-896fix) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/fbd9b4bc02cb9ea430d52b418858b9f71f1f4d9b/bin/git-review.py#L579)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

Not related, please drop.
</blockquote></details>

Done.

**Pull request merged**
