### PR TITLE
[Bug Fix] Fix browsing.

### PR DESCRIPTION
**Pull request by zozoens31**
This change is [Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/271)

### CODE REVIEW

**Comment by zozoens31** [comment]
:rocket:

**Review by pcorpet — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/271)* status: Missing an assignee or a reviewer, Unresolved discussions

*[a discussion](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/271#-Mbl0_syBJaiSSvwSoJV:-Mbl0_szDS-HL8mSfuhJ:b1a87c2) (no related file):*
Why do you prefer numbers for PR? in the future they could become non-numbers and the current code would just work great I believe

---

**Comment by zozoens31** [comment]
:rocket:

**Review by zozoens31 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/271)* status: Missing an assignee or a reviewer

*[a discussion](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/271#-Mbl0_syBJaiSSvwSoJV:-MblHzj62VyC35WXedH0:b-896fix) (no related file):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

Why do you prefer numbers for PR? in the future they could become non-numbers and the current code would just work great I believe
</blockquote></details>

Done.

---

**Pull request closed without merging**
