### PR TITLE
Enable the "Squash on GitHub" feature by default.

### PR DESCRIPTION
**Pull request by pcorpet**
This change is [Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/111)

### CODE REVIEW

**Comment by zozoens31** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[git-custom-commands-test/features/git-submit.feature, line 4 at r1](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/111#-L2yNCGyd47b1iAbzqlP:-L2yNCGyd47b1iAbzqlQ:bh8nxb) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/9b1d67ad3f74807d6c2aefe663a08f39e103202e/git-custom-commands-test/features/git-submit.feature#L4)):*
> ```Gherkin
> 
>   Background:
>     Given I set the environment variable "NO_GIT_SUBMIT_EXPERIMENTAL" to "1"
> ```

Shouldn't we also tes the default case?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/111)*

**Comment by zozoens31** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/111)*

**Comment by zozoens31** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/111#-:-L2yNifliBf47rOQOU4V:bnfp4nl)*

**Comment by pcorpet** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[git-custom-commands-test/features/git-submit.feature, line 4 at r1](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/111#-L2yNCGyd47b1iAbzqlP:-L2yh83wnddKzRq0cXNI:b-8f1ccy) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/9b1d67ad3f74807d6c2aefe663a08f39e103202e/git-custom-commands-test/features/git-submit.feature#L4)):*
<details><summary><i>Previously, zozoens31 (Cyrille Corpet) wrote…</i></summary><blockquote>

Shouldn't we also tes the default case?
</blockquote></details>

I added a TODO (lazy me)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/111)*

**Pull request merged**
