### PR TITLE
[Clean Code] Move auto-completions to their own folder.

### PR DESCRIPTION
**Pull request by zozoens31**
This change is [Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/384)

### CODE REVIEW

**Comment by zozoens31** [comment]
:game_die:

**Comment by zozoens31** [comment]
:rocket:

**Comment by zozoens31** [comment]
:rocket:

**Review by mlendale — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/384#-:-MrbE4rr4KSHs2vB8wBk:bnfp4nl)* status: :shipit: complete! 0 of 5 files reviewed, all discussions resolved

**Pull request merged**
