### PR TITLE
[Submit] Allow to continue on a pending rebase.

### PR DESCRIPTION
**Pull request by zozoens31**
This change is [Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/376)

### CODE REVIEW

**Comment by zozoens31** [comment]
:game_die:

**Comment by zozoens31** [comment]
:rocket:

**Review by pcorpet — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/376)* status: LGTM missing from one of: pcorpet, Unresolved discussions

*[a discussion](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/376#-Mr32XScEuQ6Q61nFrgr:-Mr32XSd6ncen89jLGQA:b3paxul) (no related file):*
I'm not sure how this would work: should I run it with --continue, or with --rebase AND --continue?

---

**Comment by zozoens31** [comment]
:rocket:

**Review by zozoens31 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/376)* status: LGTM missing from one of: pcorpet

*[a discussion](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/376#-Mr32XScEuQ6Q61nFrgr:-Mr33pRx-7eibUi9Ri3Z:bew7bbd) (no related file):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

I'm not sure how this would work: should I run it with --continue, or with --rebase AND --continue?
</blockquote></details>

Do you want to continue rebasing or submitting? I believe the two are not required. But both work

---

**Review by pcorpet — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/376#-:-Mr6wMqmE-QdhWvkf7M7:bnfp4nl)* status: :shipit: complete! 0 of 1 files reviewed, all discussions resolved

**Pull request merged**
