### PR TITLE
[Clean Code] Use streamed output from subprocess when useful.

### PR DESCRIPTION
**Pull request by zozoens31**
This change is [Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/366)

### CODE REVIEW

**Comment by zozoens31** [comment]
:game_die:

**Comment by zozoens31** [comment]
:rocket:

**Comment by zozoens31** [comment]
:rocket:

**Review by mlendale — COMMENTED** [review]
+@pcorpet 

> *[Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/366#-:-MqZLzqs4BVwPzT7TTiG:bv2wshd)* status: LGTM missing from one of: mlendale,pcorpet

**Review by pcorpet — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/366#-:-MqZc92vDRAfORORNVBF:bnfp4nl)* status: Unresolved discussions (bin/git-submit.py:r1 line 46)

___
*[bin/git-submit.py, line 46 at r1](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/366#-MqZbzj6AV8WTdBPn5KQ:-MqZbzj6AV8WTdBPn5KR:b1yby4v) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/b000fdcac1c906930a46f9f71c550ef832a2faaa/bin/git-submit.py#L46)):*
> ```Python
>         raise ValueError(f'Unable to find executable {args[0]}')
>     stdout = io.StringIO()
>     with subprocess.Popen([executable] + list(args[1:]), text=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT) as proc:
> ```

line too long

**Review by zozoens31 — COMMENTED** [review]
+reviewer:@pcorpet 

> *[Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/366#-:-MqZkI3Q89rdACa13T7A:b-4erzco)* status: :shipit: complete! 0 of 1 files reviewed, 1 unresolved discussion

___
*[bin/git-submit.py, line 46 at r1](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/366#-MqZbzj6AV8WTdBPn5KQ:-MqZkJwSE3nfZa7p4mq9:b-896fix) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/b000fdcac1c906930a46f9f71c550ef832a2faaa/bin/git-submit.py#L46)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

line too long
</blockquote></details>

Done.

**Pull request merged**
