### PR TITLE
[Clean Code] Cache branch getting functions.

### PR DESCRIPTION
**Pull request by zozoens31**
This change is [Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/237)

### CODE REVIEW

**Comment by zozoens31** [comment]
:rocket:

**Review by pcorpet — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/237#-:-MbC8r0f2WlF_9Mlv7Cx:bnfp4nl)* status: Unresolved discussions (bin/git-review.py:r1 line 57)

___
*[bin/git-review.py, line 57 at r1](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/237#-MbC8Yk7DT7dhRhaM2nl:-MbC8Yk7DT7dhRhaM2nm:b-o0doq) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/a810f1560404ed44daf121bd80b60aedca818a2a/bin/git-review.py#L57)):*
> ```Python
> 
> 
> @functools.lru_cache(maxsize=None)
> ```

drop the maxsize=None: you have no argument so there will always be only one entry in the cache so let's keep it as simle as posssible. Same below.

**Review by zozoens31 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/237)* status: :shipit: complete! all files reviewed, 1 unresolved discussion

___
*[bin/git-review.py, line 57 at r1](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/237#-MbC8Yk7DT7dhRhaM2nl:-MbDlY4H9ATYzCbvf_sw:bt0lfem) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/a810f1560404ed44daf121bd80b60aedca818a2a/bin/git-review.py#L57)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

drop the maxsize=None: you have no argument so there will always be only one entry in the cache so let's keep it as simle as posssible. Same below.
</blockquote></details>

Actually, the lru_cache is simpler when there's no maxsize, it doesn't need to keep track of the recent uses. I guess it might be over-optimization, though

**Comment by zozoens31** [comment]
:rocket:

**Pull request merged**
