### PR TITLE
Add git submit test scenarios when local repo is late compared to origin/master.

### PR DESCRIPTION
**Pull request by pcorpet**
This change is [Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/31)

### CODE REVIEW

**Comment by pcorpet** [comment]
+@everett-wetchler I'm trying to reproduce #24 but it seems to work (well `git submit` fails when there's a conflict, but there's no infinite loop).

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/31#-:-KGWOGOBm7w4YRcho8mu:1506892643)*

**Comment by everett-wetchler** [comment]
Hmm. I'm having trouble totally figuring out this mock git setup, but basically I think it's not quite testing the case I'm seeing. Here's the steps I took to reproduce.
```
git clone git@github.com:bayesimpact/learning.git
cd learning
git branch ew-test-a
git branch ew-test-b
git checkout ew-test-a
echo "foo" > tmp.txt
git add -A
git commit -m "tmp commit branch A"
git push -u origin ew-test-a
git checkout ew-test-b
echo "bar" > tmp.txt
git add -A
git commit -m "tmp commit branch B"
git push -u origin ew-test-b
git submit
git checkout ew-test-a
git submit
# Infinite loop experienced here
```

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/31#-:-KGnusuqY_lCjnJ_i74q:-1969085436)*

**Comment by pcorpet** [comment]
I ran your list of commands but didn't get the inifinite loop. Things we can check:
- give me your Git config: `git config --global -l` `git config --local -l` and `git config --system -l`
- try running the commands above from the docker test: in this repo, run `docker-compose run --rm test /bin/bash` then do the list of commands you want to to trigger the infinite loop. Note that you'll need to setup the `user.email` config:  `git config --global user.email "you@example.com"`
- make sure to update your git-submit: `~/.bayes-developer-setup/install.sh`

...

**Comment by everett-wetchler** [comment]
Updated my bayes-developer-setup and still get the same issue. Here's my git configurations:
```
$ git config --global -l

user.name=Everett Wetchler
user.email=everett.wetchler@bayesimpact.org
core.editor=sublime -n -w
core.excludesfile='~/.gitignore'
push.default=tracking
color.ui=true
mergetool.nbmerge.cmd=nbmerge $LOCAL $BASE $REMOTE $MERGED
filter.media.required=true
filter.media.clean=git media clean %f
filter.media.smudge=git media smudge %f
init.templatedir=~/.git_template
filter.lfs.clean=git-lfs clean %f
filter.lfs.smudge=git-lfs smudge %f
filter.lfs.required=true
```
```
$ git config --local -l
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
core.ignorecase=true
core.precomposeunicode=true
remote.origin.url=git@github.com:bayesimpact/learning.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.master.remote=origin
branch.master.merge=refs/heads/master
branch.ew-test-a.remote=origin
branch.ew-test-a.merge=refs/heads/ew-test-a
```
```
$ git config --system -l
fatal: unable to read config file '/Applications/Xcode.app/Contents/Developer/usr/etc/gitconfig': No such file or directory
```
(I guess that means I have no system level config?)


And here's the infinite loop I get:
```
First, rewinding head to replay your work on top of it...
Applying: tmp commit branch A
Using index info to reconstruct a base tree...
Falling back to patching base and 3-way merge...
Auto-merging tmp.txt
CONFLICT (add/add): Merge conflict in tmp.txt
Failed to merge in the changes.
Patch failed at 0001 tmp commit branch A
The copy of the patch that failed is found in:
   /Users/everettwetchler/src/learning/.git/rebase-apply/patch

When you have resolved this problem, run "git rebase --continue".
If you prefer to skip this patch, run "git rebase --skip" instead.
To check out the original branch and stop rebasing, run "git rebase --abort".

First, rewinding head to replay your work on top of it...
```

**Comment by everett-wetchler** [comment]
As discussed on slack, the issue was on my machine. I had an old git-submit script installed at `/usr/local/bin/git-submit` which was being run, instead of the one at `~/.bayes-developer-setup` (which is on the path, but found later). Must have been a holdover from an earlier setup. Maybe before this repo.

<details><summary><i>Previously, everett-wetchler (Everett Wetchler) wrote…</i></summary>
> Updated my bayes-developer-setup and still get the same issue. Here's my git configurations:
> 
> ```
> 
> $ git config --global -l
> 
> 
> 
> user.name=Everett Wetchler
> 
> user.email=everett.wetchler@bayesimpact.org
> 
> core.editor=sublime -n -w
> 
> core.excludesfile='~/.gitignore'
> 
> push.default=tracking
> 
> color.ui=true
> 
> mergetool.nbmerge.cmd=nbmerge $LOCAL $BASE $REMOTE $MERGED
> 
> filter.media.required=true
> 
> filter.media.clean=git media clean %f
> 
> filter.media.smudge=git media smudge %f
> 
> init.templatedir=~/.git_template
> 
> filter.lfs.clean=git-lfs clean %f
> 
> filter.lfs.smudge=git-lfs smudge %f
> 
> filter.lfs.required=true
> 
> ```
> 
> ```
> 
> $ git config --local -l
> 
> core.repositoryformatversion=0
> 
> core.filemode=true
> 
> core.bare=false
> 
> core.logallrefupdates=true
> 
> core.ignorecase=true
> 
> core.precomposeunicode=true
> 
> remote.origin.url=git@github.com:bayesimpact/learning.git
> 
> remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
> 
> branch.master.remote=origin
> 
> branch.master.merge=refs/heads/master
> 
> branch.ew-test-a.remote=origin
> 
> branch.ew-test-a.merge=refs/heads/ew-test-a
> 
> ```
> 
> ```
> 
> $ git config --system -l
> 
> fatal: unable to read config file '/Applications/Xcode.app/Contents/Developer/usr/etc/gitconfig': No such file or directory
> 
> ```
> 
> (I guess that means I have no system level config?)
> 
> 
> 
> 
> 
> And here's the infinite loop I get:
> 
> ```
> 
> First, rewinding head to replay your work on top of it...
> 
> Applying: tmp commit branch A
> 
> Using index info to reconstruct a base tree...
> 
> Falling back to patching base and 3-way merge...
> 
> Auto-merging tmp.txt
> 
> CONFLICT (add/add): Merge conflict in tmp.txt
> 
> Failed to merge in the changes.
> 
> Patch failed at 0001 tmp commit branch A
> 
> The copy of the patch that failed is found in:
> 
>    /Users/everettwetchler/src/learning/.git/rebase-apply/patch
> 
> 
> 
> When you have resolved this problem, run "git rebase --continue".
> 
> If you prefer to skip this patch, run "git rebase --skip" instead.
> 
> To check out the original branch and stop rebasing, run "git rebase --abort".
> 
> 
> 
> First, rewinding head to replay your work on top of it...
> 
> ```</details>


---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/31#-:-KHN2tCuK9kJ03n1MKx8:232632519)*

**Comment by everett-wetchler** [comment]
:lgtm:

<details><summary><i>Previously, everett-wetchler (Everett Wetchler) wrote…</i></summary>
> As discussed on slack, the issue was on my machine. I had an old git-submit script installed at `/usr/local/bin/git-submit` which was being run, instead of the one at `~/.bayes-developer-setup` (which is on the path, but found later). Must have been a holdover from an earlier setup. Maybe before this repo.</details>


---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/31#-:-KHN3DrpZc1JMy9LP9zj:1417088721)*

**Pull request merged**
