### PR TITLE
Make it easier to test reviewable-to-slack integration

### PR DESCRIPTION
**Pull request by florianjourda**
This change is [Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/90)

### CODE REVIEW

**Comment by pcorpet** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[lambda-reviewable-to-slack/README.md, line 29 at r1](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/90#-Kw5lq4d0K_Obit5TFrX:-Kw5lq4d0K_Obit5TFrY:b-x5kqhk) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/87cc26c8707015e51eb43569e0186c7441e1d334/lambda-reviewable-to-slack/README.md#L29)):*
> ```Markdown
> ```
> docker-compose run lambda-reviewable-to-slack-test bash
> cd manual_flask_test
> ```

I prefer if all commands work directly from the root: you can use $0 in the bash script if you need to locate where it is.

---

*[lambda-reviewable-to-slack/manual_flask_test/test-flask-endpoint.sh, line 7 at r1](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/90#-Kw5lZmbHhYTwGPVz0qX:-Kw5lZmcOC4h9qfQBHYz:b-2txwq7) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/87cc26c8707015e51eb43569e0186c7441e1d334/lambda-reviewable-to-slack/manual_flask_test/test-flask-endpoint.sh#L7)):*
> ```Shell
> # Usage:
> # ./test-flask-endpoint issue_comment github_notification_issue_comment.json
> EVENT_TYPE_TO_TEST="$1"
> ```

make them readonly please

---

*[lambda-reviewable-to-slack/manual_flask_test/test-flask-endpoint.sh, line 11 at r1](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/90#-Kw5lDtm8BIS2a2mInkD:-Kw5lDtm8BIS2a2mInkE:b8vrwu) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/87cc26c8707015e51eb43569e0186c7441e1d334/lambda-reviewable-to-slack/manual_flask_test/test-flask-endpoint.sh#L11)):*
> ```Shell
> 
> # As auto-reload of Flask doesn't work inside the Docker container, we restart the Flask process.
> echo $(ps)
> ```

why the echo?

---

*[lambda-reviewable-to-slack/manual_flask_test/test-flask-endpoint.sh, line 12 at r1](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/90#-Kw5lQH47yDupdR25Nri:-Kw5lQH5z_xvCCAjxaSH:bck0i2f) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/87cc26c8707015e51eb43569e0186c7441e1d334/lambda-reviewable-to-slack/manual_flask_test/test-flask-endpoint.sh#L12)):*
> ```Shell
> # As auto-reload of Flask doesn't work inside the Docker container, we restart the Flask process.
> echo $(ps)
> FLASK_PID=$(ps | sed -n '/[^-]flask[^-]/p' | sed 's/^ \+\([0-9]\+\).*/\1/')
> ```

I think grep is more well known for the first operation.

---

*[lambda-reviewable-to-slack/manual_flask_test/test-flask-endpoint.sh, line 12 at r1](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/90#-Kw5lV51hlSSoKxHOOGW:-Kw5lV51hlSSoKxHOOGX:bamiac7) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/87cc26c8707015e51eb43569e0186c7441e1d334/lambda-reviewable-to-slack/manual_flask_test/test-flask-endpoint.sh#L12)):*
> ```Shell
> # As auto-reload of Flask doesn't work inside the Docker container, we restart the Flask process.
> echo $(ps)
> FLASK_PID=$(ps | sed -n '/[^-]flask[^-]/p' | sed 's/^ \+\([0-9]\+\).*/\1/')
> ```

opt - for the second operation, maybe use cut

---

*[lambda-reviewable-to-slack/manual_flask_test/test-flask-endpoint.sh, line 14 at r1](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/90#-Kw5lYC5RotRh-c977Sx:-Kw5lYC5RotRh-c977Sy:b8vrwu) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/87cc26c8707015e51eb43569e0186c7441e1d334/lambda-reviewable-to-slack/manual_flask_test/test-flask-endpoint.sh#L14)):*
> ```Shell
> FLASK_PID=$(ps | sed -n '/[^-]flask[^-]/p' | sed 's/^ \+\([0-9]\+\).*/\1/')
> if [ -n "$FLASK_PID" ]; then
>   echo $FLASK_PID
> ```

why the echo?

---

*[lambda-reviewable-to-slack/manual_flask_test/test-flask-endpoint.sh, line 21 at r1](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/90#-Kw5ldSws5gkkq2Ukj5l:-Kw5ldSws5gkkq2Ukj5m:b-yadcsg) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/87cc26c8707015e51eb43569e0186c7441e1d334/lambda-reviewable-to-slack/manual_flask_test/test-flask-endpoint.sh#L21)):*
> ```Shell
> flask run &
> 
> # Give time to Flash to start
> ```

trailing dot please

---

*[lambda-reviewable-to-slack/manual_flask_test/test-flask-endpoint.sh, line 24 at r1](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/90#-Kw5lgu-QdnTFlPH7XlG:-Kw5lgu-QdnTFlPH7XlH:biev2my) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/87cc26c8707015e51eb43569e0186c7441e1d334/lambda-reviewable-to-slack/manual_flask_test/test-flask-endpoint.sh#L24)):*
> ```Shell
> sleep 1
> 
> RESPONSE=$(curl -X POST -H "X-GitHub-Event: $EVENT_TYPE_TO_TEST" -H "Content-Type: application/json" --data @$PAYLOAD_TO_TEST http://127.0.0.1:5000/handle_github_notification)
> ```

what happens if you just leave the curl command: do not store it in RESPONSE so that you don't need to echo just below.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/90)*

**Comment by florianjourda** [comment]
Review status: 2 of 4 files reviewed at latest revision, 8 unresolved discussions.

---

*[lambda-reviewable-to-slack/README.md, line 29 at r1](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/90#-Kw5lq4d0K_Obit5TFrX:-Kw5nrYYj4n68tq_6fRg:b-896fix) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/87cc26c8707015e51eb43569e0186c7441e1d334/lambda-reviewable-to-slack/README.md#L29)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

I prefer if all commands work directly from the root: you can use $0 in the bash script if you need to locate where it is.
</blockquote></details>

Done.

---

*[lambda-reviewable-to-slack/manual_flask_test/test-flask-endpoint.sh, line 7 at r1](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/90#-Kw5lZmbHhYTwGPVz0qX:-Kw5nsdRAxU9r_h5mbS5:b-896fix) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/87cc26c8707015e51eb43569e0186c7441e1d334/lambda-reviewable-to-slack/manual_flask_test/test-flask-endpoint.sh#L7)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

make them readonly please
</blockquote></details>

Done.

---

*[lambda-reviewable-to-slack/manual_flask_test/test-flask-endpoint.sh, line 11 at r1](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/90#-Kw5lDtm8BIS2a2mInkD:-Kw5ntG1VRDf0jrHPxeH:b-896fix) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/87cc26c8707015e51eb43569e0186c7441e1d334/lambda-reviewable-to-slack/manual_flask_test/test-flask-endpoint.sh#L11)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

why the echo?
</blockquote></details>

Done.

---

*[lambda-reviewable-to-slack/manual_flask_test/test-flask-endpoint.sh, line 12 at r1](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/90#-Kw5lQH47yDupdR25Nri:-Kw5nww1A72OIUYWVAIt:b-896fix) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/87cc26c8707015e51eb43569e0186c7441e1d334/lambda-reviewable-to-slack/manual_flask_test/test-flask-endpoint.sh#L12)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

I think grep is more well known for the first operation.
</blockquote></details>

Done.

---

*[lambda-reviewable-to-slack/manual_flask_test/test-flask-endpoint.sh, line 12 at r1](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/90#-Kw5lV51hlSSoKxHOOGW:-Kw5o188MfWUsXEmAmPf:brokobc) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/87cc26c8707015e51eb43569e0186c7441e1d334/lambda-reviewable-to-slack/manual_flask_test/test-flask-endpoint.sh#L12)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

opt - for the second operation, maybe use cut
</blockquote></details>

I will think about it next time

---

*[lambda-reviewable-to-slack/manual_flask_test/test-flask-endpoint.sh, line 21 at r1](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/90#-Kw5ldSws5gkkq2Ukj5l:-Kw5o5gkQOiyHqTwPvCZ:b-896fix) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/87cc26c8707015e51eb43569e0186c7441e1d334/lambda-reviewable-to-slack/manual_flask_test/test-flask-endpoint.sh#L21)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

trailing dot please
</blockquote></details>

Done.

---

*[lambda-reviewable-to-slack/manual_flask_test/test-flask-endpoint.sh, line 24 at r1](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/90#-Kw5lgu-QdnTFlPH7XlG:-Kw5oGvc3TZlY4DWXRDH:b-896fix) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/87cc26c8707015e51eb43569e0186c7441e1d334/lambda-reviewable-to-slack/manual_flask_test/test-flask-endpoint.sh#L24)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

what happens if you just leave the curl command: do not store it in RESPONSE so that you don't need to echo just below.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/90)*

**Comment by florianjourda** [comment]
Review status: 2 of 4 files reviewed at latest revision, 8 unresolved discussions.

---

*[lambda-reviewable-to-slack/manual_flask_test/test-flask-endpoint.sh, line 14 at r1](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/90#-Kw5lYC5RotRh-c977Sx:-Kw5p8iVEGwtNptrboNY:b-896fix) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/87cc26c8707015e51eb43569e0186c7441e1d334/lambda-reviewable-to-slack/manual_flask_test/test-flask-endpoint.sh#L14)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

why the echo?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/90)*

**Comment by pcorpet** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[lambda-reviewable-to-slack/manual_flask_test/test-flask-endpoint.sh, line 14 at r1](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/90#-Kw5lYC5RotRh-c977Sx:-Kw5rDf7S7UyVahyZNtX:b-p9poot) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/87cc26c8707015e51eb43569e0186c7441e1d334/lambda-reviewable-to-slack/manual_flask_test/test-flask-endpoint.sh#L14)):*
<details><summary><i>Previously, florianjourda (Florian Jourda) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

is it?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/90#-:-Kw5rFwv3aCNRDx1NDHT:bnfp4nl)*

**Comment by florianjourda** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[lambda-reviewable-to-slack/manual_flask_test/test-flask-endpoint.sh, line 14 at r1](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/90#-Kw5lYC5RotRh-c977Sx:-Kw5stWN1NXk0MCkdrfT:b-896fix) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/87cc26c8707015e51eb43569e0186c7441e1d334/lambda-reviewable-to-slack/manual_flask_test/test-flask-endpoint.sh#L14)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

is it?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/90)*

**Pull request closed without merging**
