### PR TITLE
[Hooks] Allow pre-commit hook to show why some hooks were skipped.

### PR DESCRIPTION
**Pull request by zozoens31**
This change is [Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/371)

### CODE REVIEW

**Comment by zozoens31** [comment]
:game_die:

**Comment by zozoens31** [comment]
:rocket:

**Review by pcorpet — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/371#-:-Mqyq5cKAcwwY8wtJoF3:bnfp4nl)* status: Unresolved discussions (hooks/pre-commit:r1 line 121)

___
*[hooks/pre-commit, line 121 at r1](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/371#-MqypuAh-Qq9CkObENEG:-MqypuAh-Qq9CkObENEH:b-tfoffp) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/8fd18bc59e125dc1d87d7b81132ac742042d32fb/hooks/pre-commit#L121)):*
> ```
> 
> if __name__ == '__main__':
>     unittest.main(verbosity=os.getenv('GIT_PRECOMMIT_SKIPPING_REASONS') and 2 or 0, buffer=True)
> ```

Please split it on a line above to give it a name
```py
should_show_skipping_reasons = ...
```

**Review by zozoens31 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/371)* status: :shipit: complete! all files reviewed, 1 unresolved discussion

___
*[hooks/pre-commit, line 121 at r1](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/371#-MqypuAh-Qq9CkObENEG:-Mqyrkpy9yOho3lT7Jfe:b-896fix) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/8fd18bc59e125dc1d87d7b81132ac742042d32fb/hooks/pre-commit#L121)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

Please split it on a line above to give it a name
```py
should_show_skipping_reasons = ...
```
</blockquote></details>

Done.

**Comment by zozoens31** [comment]
:rocket:

**Pull request merged**
