### PR TITLE
[Hooks] Add a hook about files not in Bazel.

### PR DESCRIPTION
**Pull request by zozoens31**
This change is [Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/369)

### CODE REVIEW

**Comment by zozoens31** [comment]
:game_die:

**Comment by zozoens31** [comment]
:rocket:

**Review by mlendale — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/369)* status: LGTM missing from one of: mlendale, Unresolved discussions (hooks/pre-commit:r1 line 89)

___
*[hooks/pre-commit, line 89 at r1](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/369#-MqsEbl8BjLJnzNDdPBP:-MqsEbl8BjLJnzNDdPBQ:b7cn2kz) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/33e870bed63edd91cc4ab8f25edffe0063d661b8/hooks/pre-commit#L89)):*
> ```
>             _run('bazel', 'query', f'set({" ".join(changed_files)})')
>         except subprocess.CalledProcessError:
>             self.fail('Some diffed files are not in Bazel dependency tree')
> ```

Why not use the word "changed"?

**Review by mlendale — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/369#-:-MqsEgj083zetVjShGGK:bg7igkv)* status: Unresolved discussions (hooks/pre-commit:r1 line 89)

**Review by zozoens31 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/369)* status: :shipit: complete! 0 of 1 files reviewed, 1 unresolved discussion

___
*[hooks/pre-commit, line 89 at r1](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/369#-MqsEbl8BjLJnzNDdPBP:-MqtA4hg8Alb_l3pbOIo:b-896fix) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/33e870bed63edd91cc4ab8f25edffe0063d661b8/hooks/pre-commit#L89)):*
<details><summary><i>Previously, mlendale (Sil Endale Ahanda) wrote…</i></summary><blockquote>

Why not use the word "changed"?
</blockquote></details>

Done.

**Comment by zozoens31** [comment]
:rocket:

**Pull request merged**
