### PR TITLE
[Clean Code] Prepare the precommit hook for multiple validators.

### PR DESCRIPTION
**Pull request by zozoens31**
This change is [Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/339)

### CODE REVIEW

**Comment by zozoens31** [comment]
:rocket:

**Comment by zozoens31** [comment]
:rocket:

**Review by zozoens31 — COMMENTED** [review]
+@mlendale +reviewer:@mlendale Not sure why git-review assigned an absent engineer...

> *[Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/339#-:-MpRTvsr9fZnI22ZYwrb:bx1llj8)* status: LGTM missing from one of: pcorpet,mlendale

**Review by mlendale — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/339#-:-MpR_21x9sXMDIAUx3IE:bnfp4nl)* status: :shipit: complete! 0 of 1 files reviewed, all discussions resolved

**Pull request merged**
