### PR TITLE
Creates an installer for the developer setup.

### PR DESCRIPTION
**Pull request by pcorpet**
For #9

---
This change is [Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/12)

### CODE REVIEW

**Comment by everett-wetchler** [comment]
*[install.sh, line 63 \[r1\]](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/12#-KCyxQPV2f67csyHx5PO-r1-63:-KD26FqwTIZwmV0qpKv2:886746386) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/a13d070319ca445747338088be19af368cde081b/install.sh#L63)):*
Ah OK. I'm just reading the bash more closely now, and realizing it removes and re-adds these lines, which was my only concern so that we could repeatedly run the command without issue.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/12)*

**Comment by everett-wetchler** [comment]
*[install.sh, line 66 \[r2\]](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/12#-KD25e8_8IdjNUqZYtiq:-KD25e8_8IdjNUqZYtir:170110531) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/a67bedf7ab6f5c6e57fe586328bb26b80c585767/install.sh#L66)):*
I don't understand this change?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/12)*

**Comment by everett-wetchler** [comment]
LGTM -- one thing I didnt understand but non-blocking, merge at will.

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/12#-:-KD27XkZLFsPhna_5Cie:-1467792246)*

**Comment by everett-wetchler** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/12#-:-KD27biJCKGAl3_HBo0O:1417088721)*

**Comment by pcorpet** [comment]
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[install.sh, line 66 \[r2\]](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/12#-KD25e8_8IdjNUqZYtiq:-KD3aQyWB2b5dVZBIZ8r:-1253602504) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/a67bedf7ab6f5c6e57fe586328bb26b80c585767/install.sh#L66)):*
I think I was trying to be clever, but went only halfway. I've replaced it by a line that:
1. makes sure that we only add the new path if it's not already there
2. abstract the fact that when the MANPATH is empty it's equivalent as being the value of $(manpath)

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/12)*

**Pull request merged**
