### PR TITLE
Display comments from reviewable in slack integration

### PR DESCRIPTION
**Pull request by florianjourda**
This change is [Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/93)

### CODE REVIEW

**Comment by pcorpet** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/93#-Kw99dBwCLnThpnDYwUJ:-Kw99dBwCLnThpnDYwUK:bjbjpy) (no related file):*
This is a comment at the top level, but not part of the "main" comment in the thread above.

---

*[lambda-reviewable-to-slack/reviewable_to_slack.py, line 188 at r1](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/93#-Kw986zlkJuIOox68kMI:-Kw986zlkJuIOox68kMJ:bll27w1) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/a6dd392891102f09b4ff61ab27c263d5615352b7/lambda-reviewable-to-slack/reviewable_to_slack.py#L188)):*
> ```Python
>     issue = github_notification['issue']
>     if 'pull_request' not in issue:
>         # This can happen when editing directly the source code on Github without going through a
> ```

I guess this can also happen if I push a branch from the commandline without creating a pull request.

---

*[lambda-reviewable-to-slack/reviewable_to_slack.py, line 442 at r1](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/93#-Kw99RAohtaq13pKiYMF:-Kw99RAohtaq13pKiYMG:bkblla2) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/a6dd392891102f09b4ff61ab27c263d5615352b7/lambda-reviewable-to-slack/reviewable_to_slack.py#L442)):*
> ```Python
> 
> 
> def _get_comment_parts(comment_body):
> ```

How are handled comment threads that are at the top level, but not part of the main comment? Like the example I added in this PR?

---

*[lambda-reviewable-to-slack/reviewable_to_slack.py, line 445 at r1](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/93#-Kw9A0qDLo-lYuCIBvOk:-Kw9A0qDLo-lYuCIBvOl:bc2i9iy) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/a6dd392891102f09b4ff61ab27c263d5615352b7/lambda-reviewable-to-slack/reviewable_to_slack.py#L445)):*
> ```Python
>     # If there is no main comment the format of the comment is a bit weird at the beginning,
>     # and needs to be normalized to allow us to split the different part more easily.
>     comment_body = re.sub(r'^\n\n\n\nReview status:', r'\n\n---\n\nReview status:', comment_body)
> ```

Why did you decide not to compile the regexp anymore?

---

*[lambda-reviewable-to-slack/reviewable_to_slack.py, line 449 at r1](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/93#-Kw9958DcaEuNCXGVmTe:-Kw9958DcaEuNCXGVmTf:b-lzkxcg) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/a6dd392891102f09b4ff61ab27c263d5615352b7/lambda-reviewable-to-slack/reviewable_to_slack.py#L449)):*
> ```Python
>     # main_comment will be '' if the substitution happened above.
>     main_comment = _replace_emoji_image_by_emoji_name(comment_parts[0])
>     unused_review_status = comment_parts[1]
> ```

I think that you're not absolutely certain to always have 2 parts (if the body does not contain '\n\n---\n\n' in it. Instead of crashing I would silently assume that there's only a main comment.

---

*[lambda-reviewable-to-slack/reviewable_to_slack.py, line 464 at r1](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/93#-Kw99qE1sInBc6E_8248:-Kw99qE1sInBc6E_8249:b-k3yz85) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/a6dd392891102f09b4ff61ab27c263d5615352b7/lambda-reviewable-to-slack/reviewable_to_slack.py#L464)):*
> ```Python
>         raise SetupException('Need to define _GITHUB_PERSONAL_ACCESS_TOKEN env variable.')
>     auth = tuple(_GITHUB_PERSONAL_ACCESS_TOKEN.split(':'))
>     # TODO(florian): Get items on page > 1 if necessary.
> ```

I'll try to restrain myself to 100 comments :-)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/93#-:-Kw9AB7RxHZnPClUfykj:bnfp4nl)*

**Comment by florianjourda** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[a discussion](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/93#-Kw9Z8n96HoSRIbYIIJM:-Kw9Z8n96HoSRIbYIIJN:bk0k3zo) (no related file):*
Another test

---

*[lambda-reviewable-to-slack/reviewable_to_slack.py, line 188 at r1](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/93#-Kw986zlkJuIOox68kMI:-Kw9XYSQX2EwhE-nSH9s:b-896fix) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/a6dd392891102f09b4ff61ab27c263d5615352b7/lambda-reviewable-to-slack/reviewable_to_slack.py#L188)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

I guess this can also happen if I push a branch from the commandline without creating a pull request.
</blockquote></details>

Done.

---

*[lambda-reviewable-to-slack/reviewable_to_slack.py, line 445 at r1](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/93#-Kw9A0qDLo-lYuCIBvOk:-Kw9XbmFBfy1t8s3Jxu-:b-r0kiod) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/a6dd392891102f09b4ff61ab27c263d5615352b7/lambda-reviewable-to-slack/reviewable_to_slack.py#L445)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

Why did you decide not to compile the regexp anymore?
</blockquote></details>

I started doing it, but I struggled to find names that would be clear enough. I will give it another try.

---

*[lambda-reviewable-to-slack/reviewable_to_slack.py, line 464 at r1](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/93#-Kw99qE1sInBc6E_8248:-Kw9XzgkTQFibPkycEe3:bc4dau7) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/a6dd392891102f09b4ff61ab27c263d5615352b7/lambda-reviewable-to-slack/reviewable_to_slack.py#L464)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

I'll try to restrain myself to 100 comments :-)
</blockquote></details>

No you are good, you can give 1000 inline comments, it's just it will fail at 101 back and forth between reviewer and reviewee :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/93)*

**Comment by florianjourda** [comment]
Some test

---

Review status: all files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/93#-:-Kw9ZV7iMWGNaGLRr1LH:b80jmih)*

**Comment by florianjourda** [comment]
Review status: 0 of 2 files reviewed at latest revision, 6 unresolved discussions, some commit checks pending.

---

*[a discussion](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/93#-Kw99dBwCLnThpnDYwUJ:-Kw9_JsYADhYDvj1Q9Ib:b39n10z) (no related file):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

This is a comment at the top level, but not part of the "main" comment in the thread above.
</blockquote></details>

Actually Reviewable shows this comment in the same format as the inline comments, which is an acceptable UX (the reviewer will get a notif telling an inline comment was added), so we are good

---

*[lambda-reviewable-to-slack/reviewable_to_slack.py, line 442 at r1](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/93#-Kw99RAohtaq13pKiYMF:-Kw9e2L4ewXUhhlqLNJG:brscf2e) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/a6dd392891102f09b4ff61ab27c263d5615352b7/lambda-reviewable-to-slack/reviewable_to_slack.py#L442)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

How are handled comment threads that are at the top level, but not part of the main comment? Like the example I added in this PR?
</blockquote></details>

As inline comments (CF above) so we are good.

---

*[lambda-reviewable-to-slack/reviewable_to_slack.py, line 449 at r1](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/93#-Kw9958DcaEuNCXGVmTe:-Kw9fnVyrep7yhDqwFC9:b-d5ygnu) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/a6dd392891102f09b4ff61ab27c263d5615352b7/lambda-reviewable-to-slack/reviewable_to_slack.py#L449)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

I think that you're not absolutely certain to always have 2 parts (if the body does not contain '\n\n---\n\n' in it. Instead of crashing I would silently assume that there's only a main comment.
</blockquote></details>

Good catch, this happens when commenting directly from Github

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/93)*

**Pull request merged**
