### PR TITLE
[Hooks] Add a pre-commit hook about Bazel BUILD files.

### PR DESCRIPTION
**Pull request by zozoens31**
This change is [Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/340)

### CODE REVIEW

**Comment by zozoens31** [comment]
:rocket:

**Review by mlendale — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/340#-:-MpfgJiE6JXHHlF4FKi4:bnfp4nl)* status: Unresolved discussions (hooks/pre-commit:r3 line 44)

___
*[hooks/pre-commit, line 44 at r3](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/340#-Mpffkup1jx0DfbzOWzP:-MpffkuqDJQD1godjK9W:b-1h9mau) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/8488cb2027eb6b891a37e9fb6ecb678c84a55e59/hooks/pre-commit#L44)):*
> ```
>   diff_files --name-only -- '**/BUILD' > "$changed_builds"
>   diff_files --name-only -G'^(|from \S* )import.*' | sed 's|/[^/]+$|/BUILD|' > "$changed_imports"
>   unchanged_builds="$(sort "$changed_imports" "$changed_builds" "$changed_builds" | uniq -u)"
> ```

Why twice $change_builds?
___
*[hooks/pre-commit, line 50 at r3](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/340#-MpfgCFM9hcqiz0btQx0:-MpfgCFN0A9F0HFYaUDl:b5s2t2b) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/8488cb2027eb6b891a37e9fb6ecb678c84a55e59/hooks/pre-commit#L50)):*
> ```
>   fi
>   >&2 say "BUILD files to updates:"
>   >&2 say "$unchanged_builds"
> ```

I'd find a more explicit name for that.

**Comment by zozoens31** [comment]
:rocket:

**Review by zozoens31 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/340)* status: :shipit: complete! 0 of 1 files reviewed, 2 unresolved discussions

___
*[hooks/pre-commit, line 44 at r3](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/340#-Mpffkup1jx0DfbzOWzP:-MpfqP6C7A00-BQGYjq-:b-nabeen) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/8488cb2027eb6b891a37e9fb6ecb678c84a55e59/hooks/pre-commit#L44)):*
<details><summary><i>Previously, mlendale (Sil Endale Ahanda) wrote…</i></summary><blockquote>

Why twice $change_builds?
</blockquote></details>

We want to find the changed_imports that are not in changed_builds. If we look for uniques elements of `[...changed_imports, ...changed_builds, ...changed_builds]`, we'll get only the unique elements of `changed_imports` which are not in `changed_builds`.
This is [set difference in bash](https://stackoverflow.com/a/13038235/4482064)
___
*[hooks/pre-commit, line 50 at r3](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/340#-MpfgCFM9hcqiz0btQx0:-Mpfrmb-5NkgJaUSdPB_:b-896fix) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/8488cb2027eb6b891a37e9fb6ecb678c84a55e59/hooks/pre-commit#L50)):*
<details><summary><i>Previously, mlendale (Sil Endale Ahanda) wrote…</i></summary><blockquote>

I'd find a more explicit name for that.
</blockquote></details>

Done.

**Pull request merged**
