### PR TITLE
[Submit] Add the --rebase option.

### PR DESCRIPTION
**Pull request by zozoens31**
This change is [Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/342)

### CODE REVIEW

**Comment by zozoens31** [comment]
:rocket:

**Review by pcorpet — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/342#-:-MplTP7e-TickE2tnTcP:bnfp4nl)* status: Unresolved discussions (bin/git-submit.py:r1 line 449)

___
*[bin/git-submit.py, line 449 at r1](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/342#-MplRqnJBUrHyzmBC6vw:-MplRqnJBUrHyzmBC6vx:bha4m8l) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/4334f0d054c4f0c20c9f27f6dbf112fb4f3e1aae/bin/git-submit.py#L449)):*
> ```Python
> 
> 
> def _rebase_or_fail(
> ```

So your func is called _rebase_or_fail but actually won't fail in some cases? Let's rename the whole thing: maybe `def _rebase` and `should_abort_on_error: bool = True`
___
*[bin/git-submit.py, line 544 at r1](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/342#-MplTCCPAaiYFtqbNlUv:-MplTCCPAaiYFtqbNlUw:be7ofkz) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/4334f0d054c4f0c20c9f27f6dbf112fb4f3e1aae/bin/git-submit.py#L544)):*
> ```Python
>         (such as in username@example.com). Only useful for '--abort'.''')
>     args: _Arguments = parser.parse_args()
>     should_abort = args.abort or args.rebase
> ```

Please rename the var to should_abort_autosubmission or something alike.
___
*[bin/git-submit.py, line 589 at r1](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/342#-MplSwh93iqQaoTwFCje:-MplSwh93iqQaoTwFCjf:bb6uy7h) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/4334f0d054c4f0c20c9f27f6dbf112fb4f3e1aae/bin/git-submit.py#L589)):*
> ```Python
> 
> if __name__ == '__main__':
>     logging.basicConfig(level='DEBUG')
> ```

FAR?

**Comment by zozoens31** [comment]
:rocket:

**Review by zozoens31 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/342)* status: :shipit: complete! 0 of 1 files reviewed, 3 unresolved discussions

___
*[bin/git-submit.py, line 449 at r1](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/342#-MplRqnJBUrHyzmBC6vw:-MppXSIh7jQ_IU35PAOR:b-896fix) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/4334f0d054c4f0c20c9f27f6dbf112fb4f3e1aae/bin/git-submit.py#L449)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

So your func is called _rebase_or_fail but actually won't fail in some cases? Let's rename the whole thing: maybe `def _rebase` and `should_abort_on_error: bool = True`
</blockquote></details>

Done.
___
*[bin/git-submit.py, line 544 at r1](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/342#-MplTCCPAaiYFtqbNlUv:-MppXici8VPJFbrf8rMX:b-896fix) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/4334f0d054c4f0c20c9f27f6dbf112fb4f3e1aae/bin/git-submit.py#L544)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

Please rename the var to should_abort_autosubmission or something alike.
</blockquote></details>

Done.
___
*[bin/git-submit.py, line 589 at r1](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/342#-MplSwh93iqQaoTwFCje:-MppXkPwAMdHHKfIRUyT:b-896fix) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/4334f0d054c4f0c20c9f27f6dbf112fb4f3e1aae/bin/git-submit.py#L589)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

FAR?
</blockquote></details>

Done.

**Pull request merged**
