### PR TITLE
[Clean Code] Use python tests for pre-commit hook.

### PR DESCRIPTION
**Pull request by zozoens31**
This change is [Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/363)

### CODE REVIEW

**Comment by zozoens31** [comment]
:game_die:

**Comment by zozoens31** [comment]
:rocket:

**Comment by zozoens31** [comment]
:rocket:

**Comment by zozoens31** [comment]
:rocket:

**Comment by zozoens31** [comment]
:rocket:

**Comment by zozoens31** [comment]
:rocket:

**Comment by zozoens31** [comment]
:rocket:

**Review by zozoens31 — COMMENTED** [review]
+reviewer:@emilieguth +@emilieguth 

> *[Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/363#-:-Mqn0CHSB124cSaOal5O:b-i0yj8k)* status: LGTM missing from one of: emilieguth

**Review by emilieguth — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/363#-:-MqoVAov3YPm4Gz_xBRP:bnfp4nl)* status: :shipit: complete! 0 of 6 files reviewed, all discussions resolved

**Pull request merged**
