### PR TITLE
[Clean Code] Move hub api cache mechanism to _run_hub.

### PR DESCRIPTION
**Pull request by zozoens31**
This change is [Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/267)

### CODE REVIEW

**Comment by zozoens31** [comment]
:rocket:

**Comment by zozoens31** [comment]
:rocket:

**Review by pcorpet — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/267#-:-Mbl6api2seKZk4AAiwx:bnfp4nl)* status: Unresolved discussions (bin/git-review.py:r1 line 92)

___
*[bin/git-review.py, line 92 at r1](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/267#-Mbl6Yzi1sjZiv6U0t9T:-Mbl6Yzi1sjZiv6U0t9U:b2deu3i) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/273d57fa773e3d5a5bac1beee7c0dfd8bdd6c540/bin/git-review.py#L92)):*
> ```Python
> def _run_hub(command: List[str], *, cache: Optional[int] = None, **kwargs: Any) -> str:
>     final_command = ['hub'] + command
>     if cache:
> ```

Maybe add a global option to disable hub caching entirely
___
*[bin/git-review.py, line 503 at r1](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/267#-Mbl6TO4EI_tLuhhpNe0:-Mbl6TO4EI_tLuhhpNe1:bf8kjqq) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/273d57fa773e3d5a5bac1beee7c0dfd8bdd6c540/bin/git-review.py#L503)):*
> ```Python
>             self._add_reviewers(refs, reviewers)
>             return
>         command = [
> ```

Maybe rename the var `hub_command`

**Review by zozoens31 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/267)* status: :shipit: complete! all files reviewed, 2 unresolved discussions

___
*[bin/git-review.py, line 92 at r1](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/267#-Mbl6Yzi1sjZiv6U0t9T:-MblGxwv28LITe768Kqe:b-896fix) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/273d57fa773e3d5a5bac1beee7c0dfd8bdd6c540/bin/git-review.py#L92)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

Maybe add a global option to disable hub caching entirely
</blockquote></details>

Done.
___
*[bin/git-review.py, line 503 at r1](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/267#-Mbl6TO4EI_tLuhhpNe0:-MblGygJ6TtO1jaELJWY:b-896fix) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/273d57fa773e3d5a5bac1beee7c0dfd8bdd6c540/bin/git-review.py#L503)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

Maybe rename the var `hub_command`
</blockquote></details>

Done.

**Comment by zozoens31** [comment]
:rocket:

**Pull request merged**
