### PR TITLE
[Review] Connect reviews to Lucca.

### PR DESCRIPTION
**Pull request by zozoens31**
This change is [Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/284)

### CODE REVIEW

**Comment by zozoens31** [comment]
:rocket:

**Review by emilieguth — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/284#-:-McDCPJm5MgmdmJjDkcO:bnfp4nl)* status: :shipit: complete! 0 of 1 files reviewed, all discussions resolved

**Comment by pcorpet** [comment]
:owl:

**Comment by zozoens31** [comment]
:rocket:

**Pull request merged**
