### PR TITLE
[Clean Code] Create a review if one doesn't already exists only.

### PR DESCRIPTION
**Pull request by zozoens31**
This change is [Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/258)

### CODE REVIEW

**Comment by zozoens31** [comment]
:rocket:

**Comment by zozoens31** [comment]
:rocket:

**Review by pcorpet — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/258#-:-MbaueK6DV028kEESopV:bnfp4nl)* status: Unresolved discussions (bin/git-review.py:r1 line 272)

___
*[bin/git-review.py, line 272 at r1](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/258#-MbauCwB0AM7eSWF0863:-MbauCwB0AM7eSWF0864:bsttu62) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/13d02d936f7f8b32ad6c0a59c3c593df7faf91a3/bin/git-review.py#L272)):*
> ```Python
>         return next((
>             mr for mr in self.project.merge_request.list()
>             if mr.source_branch == branch), None)
> ```

Maybe also check for the base branch of the MR.
___
*[bin/git-review.py, line 272 at r1](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/258#-MbauUZ54wd1qv9crm_m:-MbauUZ54wd1qv9crm_n:bypw7mz) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/a0306676d563500216d2574b21b829e1c9c3aebd/bin/git-review.py#L272)):*
> ```Python
>             'title': title,
>         }
>         # TODO(cyrille): Allow several reviewers
> ```

Is that TODO done?

**Review by zozoens31 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/258)* status: :shipit: complete! all files reviewed, 2 unresolved discussions

___
*[bin/git-review.py, line 272 at r1](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/258#-MbauUZ54wd1qv9crm_m:-Mbav9_K8u8K-cBTKBP3:b-896fix) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/a0306676d563500216d2574b21b829e1c9c3aebd/bin/git-review.py#L272)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

Is that TODO done?
</blockquote></details>

Done.
___
*[bin/git-review.py, line 272 at r1](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/258#-MbauCwB0AM7eSWF0863:-MbawX1tB5IuO8SRVoQ9:bqoy05r) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/13d02d936f7f8b32ad6c0a59c3c593df7faf91a3/bin/git-review.py#L272)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

Maybe also check for the base branch of the MR.
</blockquote></details>

I'd love to, but I don't have it...

**Comment by zozoens31** [comment]
:rocket:

**Pull request merged**
