### PR TITLE
[Clean Code] Fix mypy issues for git-review.

### PR DESCRIPTION
**Pull request by zozoens31**
This change is [Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/360)

### CODE REVIEW

**Comment by zozoens31** [comment]
:game_die:

**Review by pcorpet — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/360#-:-MqUYkBa2H0gSjKL9XYk:bnfp4nl)* status: Unresolved discussions (-- commits:r1 line 2)

___
*[-- commits, line 2 at r1](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/360#-MqUYhhfDQrFvgFT4imh):*
Please mention that you're also fixing pylint issues.
___
*[bin/git-review.py, line 32 at r1](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/360#-MqUYLVC8-XpSVMuO69r:-MqUYLVC8-XpSVMuO69s:btf3lm5) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/c0373cafadaa42771a46bc4fa44ad7a5412935f7/bin/git-review.py#L32)):*
> ```Python
>     from requests import exceptions
> 
>     class _GetSet:
> ```

Please add a TODO to update `requests-types`

**Review by zozoens31 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/360)* status: :shipit: complete! all files reviewed, 2 unresolved discussions

___
*[-- commits, line 2 at r1](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/360#-MqUYhhfDQrFvgFT4imh):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

Please mention that you're also fixing pylint issues.
</blockquote></details>

Done.
___
*[bin/git-review.py, line 32 at r1](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/360#-MqUYLVC8-XpSVMuO69r:-MqUkRvsEQ4LTNw3Vo8b:b-896fix) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/c0373cafadaa42771a46bc4fa44ad7a5412935f7/bin/git-review.py#L32)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

Please add a TODO to update `requests-types`
</blockquote></details>

Done.

**Comment by zozoens31** [comment]
:rocket:

**Pull request merged**
