### PR TITLE
Add instructions for use

### PR DESCRIPTION
**Pull request by akegan**
This change is [Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/56)

### CODE REVIEW

**Comment by akegan** [comment]
@mjamei FYI

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/56#-:-Kfw2vLTlCQ9d55izADY:b-9pnwqc)*

**Comment by pcorpet** [comment]
+@pcorpet 

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[README.md, line 8 at r2](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/56#-Kfw6X3GTxracsWWBJc8:-Kfw6X3GTxracsWWBJc9:bnaeduz) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/9081779697e65046f3250addd9963a25536a0049/README.md#L8)):*
> ```Markdown
> You can install it without downloading the repo yourself by downloading and
> running `install.sh` (no need to clone the repo yourself). Test your installation by verifying that hub was installed correctly.
> Running `which hub` should return something like "/Users/[username]/.bayes-developer-setup/bin/hub".
> ```

nit - this is only true on Mac, maybe write `~/.bayes-developer-setup/bin/hub` in general, or both links for mac & linux (/home/[username]/.bayes-developer-setup/bin/hub for linux)

---

*[README.md, line 30 at r2](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/56#-Kfw6HV0MEQ2L1ewspKW:-Kfw6HV0MEQ2L1ewspKX:b-7z8ly2) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/9081779697e65046f3250addd9963a25536a0049/README.md#L30)):*
> ```Markdown
> The first time you use bayes-developer-setup you'll have to login to Github. 
> 
> * Run `hub issue` and login using your username, password, and 2fa code.
> ```

This should happen automatically in the `install.sh` so no need to document it in addition.

---

*[README.md, line 35 at r2](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/56#-Kfw6O-9epekmUFkLL9K:-Kfw6O-9epekmUFkLL9L:b-tgne11) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/9081779697e65046f3250addd9963a25536a0049/README.md#L35)):*
> ```Markdown
> 
> * Run `git up` or `git rebase` to make sure your code is up to date with master (this will rebase your code)
> * Run `git review [reviewer-username]` to push your branch and open a pull request with the specified reviewer
> ```

please also document the `git review -f` when you want to update the code to review.

---

*[README.md, line 37 at r3](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/56#-Kfw6l3BalkoYxtA8cLf:-Kfw6l3BalkoYxtA8cLg:b-2l5g8e) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/a61f2e18e9a85e7d72d4241d9553fb5ad28efd33/README.md#L37)):*
> ```Markdown
> * Run `git review [reviewer-username]` to push your branch and open a pull request with the specified reviewer
> * When your PR is ready to be merged, run `git submit` to merge your PR and delete your local branch
> ```

drop the empty lines at the bottom please

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/56#-:-Kfw6U_roYlRRdCLrPIA:bv2wshd)*

**Comment by akegan** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[README.md, line 30 at r2](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/56#-Kfw6HV0MEQ2L1ewspKW:-Kfw7GMKBgA-F8Zg8JT7:b-j72fj0) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/9081779697e65046f3250addd9963a25536a0049/README.md#L30)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

This should happen automatically in the `install.sh` so no need to document it in addition.
</blockquote></details>

That didn't happen for me in install.sh, is that also because of the bashrc vs bash_profile issue?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/56)*

**Comment by pcorpet** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[README.md, line 30 at r2](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/56#-Kfw6HV0MEQ2L1ewspKW:-Kfw7ZrjYc0i8McJxxx9:b-it2pir) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/9081779697e65046f3250addd9963a25536a0049/README.md#L30)):*
<details><summary><i>Previously, akegan (Andrea Egan) wrote…</i></summary><blockquote>

That didn't happen for me in install.sh, is that also because of the bashrc vs bash_profile issue?
</blockquote></details>

probably because @mjamei fixed it between the time you installed it and now.
https://github.com/bayesimpact/bayes-developer-setup/commit/55e238509aa580770e71e9a380f60fdd025d8192

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/56)*

**Comment by pcorpet** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[README.md, line 10 at r3](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/56#-Kfw8UlwY6JGYkhIxtj0:-Kfw8UlwY6JGYkhIxtj1:b-178iux) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/a61f2e18e9a85e7d72d4241d9553fb5ad28efd33/README.md#L10)):*
> ```Markdown
> Running `which hub` should return something like "/Users/[username]/.bayes-developer-setup/bin/hub".
> 
> **Note**: This script will automatically write the necessary updates to your .bashrc file. If you use a different file (e.g. .bash_profile) you will need to move the information after install using `cat ~/.bashrc >> ~./bash_profile`. 
> ```

http://www.joshstaiger.org/archives/2005/07/bash_profile_vs.html

Maybe just detect which one to use in the install.sh, that would be easier.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/56)*

**Comment by akegan** [comment]
Review status: 0 of 1 files reviewed at latest revision, 5 unresolved discussions.

---

*[README.md, line 10 at r3](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/56#-Kfw8UlwY6JGYkhIxtj0:-KfwKzIoM94ATc_GIPPH:b-szyfgz) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/a61f2e18e9a85e7d72d4241d9553fb5ad28efd33/README.md#L10)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

http://www.joshstaiger.org/archives/2005/07/bash_profile_vs.html

Maybe just detect which one to use in the install.sh, that would be easier.
</blockquote></details>

I did not update the script to detect which one (I didn't find a good way to do it in a quick google), I just added instructions to automatically source from bashrc instead.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/56)*

**Comment by pcorpet** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks broke.

---

*[README.md, line 10 at r3](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/56#-Kfw8UlwY6JGYkhIxtj0:-KfwWlyRbqrzh2jmswI6:bhfotuy) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/a61f2e18e9a85e7d72d4241d9553fb5ad28efd33/README.md#L10)):*
<details><summary><i>Previously, akegan (Andrea Egan) wrote…</i></summary><blockquote>

I did not update the script to detect which one (I didn't find a good way to do it in a quick google), I just added instructions to automatically source from bashrc instead.
</blockquote></details>

Please add a TODO for me to fix it in `install.sh` (I'll probably add the`source .bashrc` line that you wrote in bash_profile if it exists).

---

*[README.md, line 14 at r4](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/56#-Kfw_1ZS6AdRPY19FsP3:-Kfw_1ZS6AdRPY19FsP4:bdlxz2e) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/e5831ed3bf8aeb47e85c39d0557a7121358314a1/README.md#L14)):*
> ```Markdown
> Hub is not found: This script will automatically write the necessary updates to your .bashrc file. If you use a different file (e.g. .bash_profile) you will need to move the information after install using `cat ~/.bashrc >> ~/.bash_profile` and re-run the install.
> 
> Alternatively, you can add this to your .bash_profile:
> ```

Yep I'd recommend that one in front, because the install.sh might want to update the code it entered and it would not update the other file.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/56#-:-Kfw_79OefbIbYJeFez3:bnfp4nl)*

**Comment by akegan** [comment]
need to close and reopen to fix the branch name

**Pull request closed without merging**
