### PR TITLE
Fixes #58: complain when trying to create a branch using an empty username.

### LINKED ISSUE #58: Name missing from branch if git config isn't set up
If git config user.email is not set when git review is run, then the branch will be created without the name (e.g. -add-instructions). 

git review should complain instead.

### PR DESCRIPTION
**Pull request by pcorpet**
This change is [Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/61)

### CODE REVIEW

**Comment by akegan** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[bin/git-review, line 39 at r1](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/61#-KhXuZUebc2o_GSNdpMt:-KhXuZUebc2o_GSNdpMu:b-azeqq9) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/1a7f50e5ee92c8e1e56659046110a5c4584b19f8/bin/git-review#L39)):*
> ```
>   if [ -z "${USERNAME}" ]; then
>     echo "Could not find username, most probably you need to setup an email with:" 1>&2
>     echo "  git config user.email <me@bayesimpact.org>" 1>&2
> ```

Is it worth suggesting the --global flag to ensure that the user is configured for all of their repos?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/61)*

**Comment by pcorpet** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[bin/git-review, line 39 at r1](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/61#-KhXuZUebc2o_GSNdpMt:-KhY7sah2sqvm5jIfA9j:b2kgi47) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/1a7f50e5ee92c8e1e56659046110a5c4584b19f8/bin/git-review#L39)):*
<details><summary><i>Previously, akegan (Andrea Egan) wrote…</i></summary><blockquote>

Is it worth suggesting the --global flag to ensure that the user is configured for all of their repos?
</blockquote></details>

I thought about it and decided against it:
1. if it's not configured for another repo, `git review` will complain there as well
2. they might want to use their personal email for other projects on the same computer (at least I do) and it might be problematic to have a default.

Do you agree?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/61)*

**Comment by akegan** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[bin/git-review, line 39 at r1](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/61#-KhXuZUebc2o_GSNdpMt:-KhYXU5ytrT8q6FrWyho:b-hps91i) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/1a7f50e5ee92c8e1e56659046110a5c4584b19f8/bin/git-review#L39)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

I thought about it and decided against it:
1. if it's not configured for another repo, `git review` will complain there as well
2. they might want to use their personal email for other projects on the same computer (at least I do) and it might be problematic to have a default.

Do you agree?
</blockquote></details>

Ok sounds good

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/61)*

**Comment by akegan** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/61#-:-KhYXaCft6tq-gpylnq9:bnfp4nl)*

**Pull request merged**
