### PR TITLE
[Bug Fix] Do not update assignees when updating reviewers.

### PR DESCRIPTION
**Pull request by zozoens31**
This change is [Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/302)

### CODE REVIEW

**Comment by zozoens31** [comment]
:rocket:

**Review by zozoens31 — COMMENTED** [review]
As you can see from the assignments in this CL, there is now a difference between assignee and requested reviewer

> *[Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/302#-:-MdS9yQN0Z-ManMF-U5A:b1m5q1p)* status: LGTM missing from one of: pcorpet,john-mts

**Review by pcorpet — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/302#-:-MdSGT2v1jZXyJvD8ssV:bnfp4nl)* status: Unresolved discussions (bin/git-review.py:r1 line 649)

___
*[bin/git-review.py, line 649 at r1](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/302#-MdSGMoQ5GrUo3yfI24m:-MdSGMoQ5GrUo3yfI24n:b-38v9pu) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/ba764777ebb8e781dc418087335343a291253ed0/bin/git-review.py#L649)):*
> ```Python
>         if self.engineers:
>             requested_reviewers = requested_reviewers & set(self.engineers)
>         breakpoint()
> ```

Please drop.

**Review by zozoens31 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/302)* status: :shipit: complete! all files reviewed, 1 unresolved discussion

___
*[bin/git-review.py, line 649 at r1](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/302#-MdSGMoQ5GrUo3yfI24m:-MdSLHPZ53SriYD7sLk6:b-896fix) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/ba764777ebb8e781dc418087335343a291253ed0/bin/git-review.py#L649)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

Please drop.
</blockquote></details>

Done.

**Comment by zozoens31** [comment]
:rocket:

**Pull request merged**
