### PR TITLE
[Clean Code] Use generic message on NotImplementedErrors.

### PR DESCRIPTION
**Pull request by zozoens31**
This change is [Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/248)

### CODE REVIEW

**Comment by zozoens31** [comment]
:rocket:

**Comment by zozoens31** [comment]
:rocket:

**Comment by zozoens31** [comment]
:rocket:

**Comment by zozoens31** [comment]
:rocket:

**Review by mlendale — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/248#-:-MbfxdA05x33FR510zQB:bnfp4nl)* status: Unresolved discussions

*[a discussion](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/248#-Mbfx_yt2gRvuLuESgA8:-Mbfx_yt2gRvuLuESgA9:b-5ih17r) (no related file):*
Maybe add a TODO to test it one day.

---
___
*[bin/git-review.py, line 234 at r1](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/248#-Mbfx2aJ5IireXshwhGB:-Mbfx2aJ5IireXshwhGC:b-n6d6dn) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/5dfa64948034268d48b4a0d62aeb1c398473533e/bin/git-review.py#L234)):*
> ```Python
>         raise NotImplementedError(f'Review platform not recognized. Remote URL is {remote_url}')
> 
> <<<<<<< HEAD
> ```

Please remove
___
*[bin/git-review.py, line 469 at r1](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/248#-MbfxPjo5-AdLXseeDfW:-MbfxPjo5-AdLXseeDfX:burq7g8) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/5dfa64948034268d48b4a0d62aeb1c398473533e/bin/git-review.py#L469)):*
> ```Python
>         '--browse', help='''
>         Open the review in a browser window.
>         Defaults to the remote branch attached to the current branch.''',
> ```

Is it related?

**Comment by zozoens31** [comment]
:rocket:

**Review by zozoens31 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/248)* status: :shipit: complete! 0 of 1 files reviewed, 3 unresolved discussions

*[a discussion](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/248#-Mbfx_yt2gRvuLuESgA8:-MbjovRUDnsrHfs5m52L:b-896fix) (no related file):*
<details><summary><i>Previously, mlendale (Sil Endale Ahanda) wrote…</i></summary><blockquote>

Maybe add a TODO to test it one day.
</blockquote></details>

Done.

---
___
*[bin/git-review.py, line 234 at r1](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/248#-Mbfx2aJ5IireXshwhGB:-Mbjp5NZDqVJaqblgare:b-896fix) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/5dfa64948034268d48b4a0d62aeb1c398473533e/bin/git-review.py#L234)):*
<details><summary><i>Previously, mlendale (Sil Endale Ahanda) wrote…</i></summary><blockquote>

Please remove
</blockquote></details>

Done.
___
*[bin/git-review.py, line 469 at r1](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/248#-MbfxPjo5-AdLXseeDfW:-MbjonVx1JK10btphSIl:b32w12) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/5dfa64948034268d48b4a0d62aeb1c398473533e/bin/git-review.py#L469)):*
<details><summary><i>Previously, mlendale (Sil Endale Ahanda) wrote…</i></summary><blockquote>

Is it related?
</blockquote></details>

No

**Pull request merged**
