### PR TITLE
[Clean Code] Select the local default branch faster.

### PR DESCRIPTION
**Pull request by zozoens31**
This change is [Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/368)

### CODE REVIEW

**Comment by zozoens31** [comment]
:rocket:

**Review by zozoens31 — COMMENTED** [review]
+reviewer:@pcorpet +@pcorpet 

> *[Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/368#-:-MqmnRSmEnEo4yQf2EPV:bn9zfsk)* status: LGTM missing from one of: pcorpet

**Review by pcorpet — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/368#-:-MqmqTrA3QHHRJWXuM0D:bnfp4nl)* status: Unresolved discussions (bin/git-submit.py:r1 line 286)

___
*[bin/git-submit.py, line 286 at r1](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/368#-MqmpmBl8Us-hImuXHJV:-MqmpmBl8Us-hImuXHJW:btrpa1) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/104adcdbeb4cbade6955d75cede07cd1fbf0d065/bin/git-submit.py#L286)):*
> ```Python
>             'git', 'for-each-ref', '--format=%(refname:short):%(upstream:short)',
>             '--sort=-committerdate', 'refs/heads')
>         if (local_and_remote := ref.split(':', 1))
> ```

please use `local_name, remote_name := ref.split`

**Review by zozoens31 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/368)* status: :shipit: complete! all files reviewed, 1 unresolved discussion

___
*[bin/git-submit.py, line 286 at r1](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/368#-MqmpmBl8Us-hImuXHJV:-MqmzqZb6LOfRDg43OBg:bsj42jl) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/104adcdbeb4cbade6955d75cede07cd1fbf0d065/bin/git-submit.py#L286)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

please use `local_name, remote_name := ref.split`
</blockquote></details>

I wish I could...

**Pull request merged**
