### PR TITLE
[Submit] Add color to output.

### PR DESCRIPTION
**Pull request by zozoens31**
This change is [Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/195)

### CODE REVIEW

**Review by pcorpet — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/195)* status: LGTM missing from one of: pcorpet, Unresolved discussions (bin/git-submit:r1 line 80)

___
*[bin/git-submit, line 80 at r1](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/195#-M_zzAXq50LmPner6kK3:-M_zzAXq50LmPner6kK4:bvw7970) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/11f504e3d44df9123ea470c0ddafbd018d3867c2/bin/git-submit#L80)):*
> ```
>   BRANCH="$START_BRANCH"
>   if [ "${BRANCH}" == "${DEFAULT_BRANCH}" ]; then
>     echo "branch required:" 1>&2
> ```

It seems that the `1>&2` is not handled anymore.

**Review by zozoens31 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/195)* status: LGTM missing from one of: pcorpet

___
*[bin/git-submit, line 80 at r1](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/195#-M_zzAXq50LmPner6kK3:-Ma-zctyBQuCQCXsL7QM:b28z4aw) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/11f504e3d44df9123ea470c0ddafbd018d3867c2/bin/git-submit#L80)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

It seems that the `1>&2` is not handled anymore.
</blockquote></details>

Done. I had mistakenly modified the `echo_with_colors` from Bob instead

**Review by pcorpet — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/195#-:-Ma2R-G64l53UDk5jMrZ:bnfp4nl)* status: Unresolved discussions (bin/echo_with_colors.sh:r2 line 2)

___
*[bin/echo_with_colors.sh, line 2 at r2](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/195#-Ma2QMIG3yD9bByplXWd:-Ma2QMIIBWbkx3Spjfmr:b8rix68) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/b3f7053a9a574feab2c8139e080c137b7c6c0145/bin/echo_with_colors.sh#L2)):*
> ```Shell
> #!/usr/bin/env bash
> # Helpers to echo strings with colors.
> ```

...to stderr.
___
*[bin/git-submit, line 100 at r2](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/195#-Ma2QXY784wxUowGo3QC:-Ma2QXY784wxUowGo3QD:b48u5jf) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/bdac17abfbe400052ce69431b71780ecf476c0fe/bin/git-submit#L100)):*
> ```
> fi
> 
> function get_pull_request_number {
> ```

Not related, is it?
___
*[bin/git-submit, line 232 at r2](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/195#-Ma2Qq1EC1dM0EDMhybR:-Ma2Qq1EC1dM0EDMhybS:b-knhhaz) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/b3f7053a9a574feab2c8139e080c137b7c6c0145/bin/git-submit#L232)):*
> ```
> if [ -z "${BRANCH_REMOTE}" ]; then
>   echo_warning "The branch ${BRANCH} is not tracked and has probably never been reviewed."
>   echo_warning "  git push -u ${BASE_REMOTE} ${BRANCH}"
> ```

To be consistant maybe we should use echo_info here.
___
*[bin/git-submit, line 273 at r2](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/195#-Ma2QyDK9GYO08AKKPEw:-Ma2QyDK9GYO08AKKPEx:brhumzt) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/b3f7053a9a574feab2c8139e080c137b7c6c0145/bin/git-submit#L273)):*
> ```
>   if [ "$(git rev-parse "${BRANCH_REMOTE}/${BRANCH_MERGE}")" != "$(git rev-parse "${BRANCH}")" ]; then
>     echo_warning "Push your branch on ${BRANCH_REMOTE}, or you'll have a hard time removing the pull request:"
>     echo_warning "  git push -f ${BRANCH_REMOTE} ${BRANCH}:${BRANCH_MERGE}"
> ```

Same here.

**Review by zozoens31 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/195)* status: :shipit: complete! 0 of 2 files reviewed, 3 unresolved discussions

___
*[bin/echo_with_colors.sh, line 2 at r2](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/195#-Ma2QMIG3yD9bByplXWd:-Ma2Xd_gETBe_kkhf5Am:b-896fix) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/b3f7053a9a574feab2c8139e080c137b7c6c0145/bin/echo_with_colors.sh#L2)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

...to stderr.
</blockquote></details>

Done.
___
*[bin/git-submit, line 100 at r2](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/195#-Ma2QXY784wxUowGo3QC:-Ma2XEPY-KSD3wfOjnC-:buketii) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/bdac17abfbe400052ce69431b71780ecf476c0fe/bin/git-submit#L100)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

Not related, is it?
</blockquote></details>

Indeed
___
*[bin/git-submit, line 232 at r2](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/195#-Ma2Qq1EC1dM0EDMhybR:-Ma2XI783O6rsvPXpK_T:b-896fix) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/b3f7053a9a574feab2c8139e080c137b7c6c0145/bin/git-submit#L232)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

To be consistant maybe we should use echo_info here.
</blockquote></details>

Done.
___
*[bin/git-submit, line 273 at r2](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/195#-Ma2QyDK9GYO08AKKPEw:-Ma2XWeC5TYd5r8IWLVY:b-896fix) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/b3f7053a9a574feab2c8139e080c137b7c6c0145/bin/git-submit#L273)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

Same here.
</blockquote></details>

Done.

**Pull request merged**
