### PR TITLE
adds instruction to the readme for logging into github before installation.

### PR DESCRIPTION
**Pull request by mjamei**
This change is [Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/54)

### CODE REVIEW

**Comment by pcorpet** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[README.md, line 8 at r1](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/54#-KfAvVod4FummHg6F1Qa:-KfAvVohcxtCItBzbdb9:b-1o20c2) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/3ac6299678174c1d00860bed4341659b3424f65b/README.md#L8)):*
> ```Markdown
> Make sure that you are logged-in to the github.com to run hub commands. You can test this by running a random hub command like
> 
>     hub issue
> ```

I suggest that instead of documenting we just call it after installing hub inside the `install.sh` script. This way it will magically work for new users without the need of reading the documentation.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/54)*

**Comment by mjamei** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[README.md, line 8 at r1](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/54#-KfAvVod4FummHg6F1Qa:-KfDhtWqnCveFbP1C3ke:bwkck08) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/3ac6299678174c1d00860bed4341659b3424f65b/README.md#L8)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

I suggest that instead of documenting we just call it after installing hub inside the `install.sh` script. This way it will magically work for new users without the need of reading the documentation.
</blockquote></details>

Just committed. Is this what you mean?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/54)*

**Comment by pcorpet** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[README.md, line 8 at r1](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/54#-KfAvVod4FummHg6F1Qa:-KfDomgSm5C2SFk5JYlR:bai0fct) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/3ac6299678174c1d00860bed4341659b3424f65b/README.md#L8)):*
<details><summary><i>Previously, mjamei (Mehdi Jamei) wrote…</i></summary><blockquote>

Just committed. Is this what you mean?
</blockquote></details>

Well, I am not sure where you committed it. Can you push again (probably a `git review -f` if you're using the regular flow).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/54)*

**Comment by mjamei** [comment]
*[README.md, line 8 at r1](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/54#-KfAvVod4FummHg6F1Qa:-KfE6dQVN7IM9PQVlgZ9:b1r4tq0) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/3ac6299678174c1d00860bed4341659b3424f65b/README.md#L8)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

Well, I am not sure where you committed it. Can you push again (probably a `git review -f` if you're using the regular flow).
</blockquote></details>

sorry! take a look now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/54)*

**Comment by pcorpet** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[install.sh, line 97 at r2](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/54#-KfE7MBb1yIDXqCUGPED:-KfE7MBb1yIDXqCUGPEE:b-qhbzk1) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/f0ad3d51476c5b51d4636dd74d72857ba01f25ab/install.sh#L97)):*
> ```Shell
> fi
> 
> #check if the user is logged in
> ```

Please make sure this follows the convention for comments (blank after #, Starts with an uppercase letter, ends with a dot).
```sh
# Check if the user is logged in GitHub with hub.
```

---

*[install.sh, line 98 at r2](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/54#-KfE7iOBHtENhN_1jV3T:-KfE7iOBHtENhN_1jV3U:bv5hqxa) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/f0ad3d51476c5b51d4636dd74d72857ba01f25ab/install.sh#L98)):*
> ```Shell
> 
> #check if the user is logged in
> hub issue
> ```

Let's use `hub ci-status` as it returns "success" if successful instead of a list of issues.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/54#-:-KfE7xGLRCiZhDtF7Xs2:bnfp4nl)*

**Comment by pcorpet** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[install.sh, line 98 at r3](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/54#-KfIw79gADJw9a8lbq1I:-KfIw79gADJw9a8lbq1J:bg60bw) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/f9dafe7186274bf64010fecd2b30ef89a31c32af/install.sh#L98)):*
> ```Shell
> 
> # Check if the user is logged in.
> if [ "$(hub ci-status)" == "success" ]; then
> ```

Oh no need for that whole block, just write `hub ci-status`: it will directly request user/password by itself if not setup properly, and otherwise display success which will look OK in the flow anyway.

---

*[install.sh, line 102 at r3](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/54#-KfIw33lKZNxVeY97-iP:-KfIw33ruEMSYKdu8bL7:bd10f4l) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/f9dafe7186274bf64010fecd2b30ef89a31c32af/install.sh#L102)):*
> ```Shell
> else
>   echo "Make sure you are signed into hub.";
> fi
> ```

be careful to keep the trailing end line as before.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/54#-:-KfIwKVMynJLsOY4NyH6:bnfp4nl)*

**Pull request merged**
