### PR TITLE
[Submit] Use pull-request show command from hub CLI.

### PR DESCRIPTION
**Pull request by zozoens31**
This change is [Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/165)

### CODE REVIEW

**Review by pcorpet — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/165)* status: LGTM missing from one of: pcorpet, Unresolved discussions (bin/git-submit:r1 line 181)

___
*[bin/git-submit, line 181 at r1](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/165#-MZrV-oQB5h8iYtS9gSP:-MZrV-oR7KLjPqJUqIfu:bcsu2ww) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/0b5a3ed6bdbae6ced0f5bcb660cb79317f551f9a/bin/git-submit#L181)):*
> ```
> 
>   # Find pull-request ID.
>   readonly PULL_REQUEST_NUMBER="$(hub pr show -h "$GITHUB_REPO_USER:$BRANCH_MERGE" -f %I)"
> ```

actually this is super useful: we could hop on the corresponding branch and just run `hub pr show -f %I`. That would mean we don't need to check or GITHUB_REPO_USER at all.

**Review by zozoens31 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/165)* status: LGTM missing from one of: pcorpet

___
*[bin/git-submit, line 181 at r1](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/165#-MZrV-oQB5h8iYtS9gSP:-MZrlfyYBwOl08I2ZyI3:b-896fix) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/0b5a3ed6bdbae6ced0f5bcb660cb79317f551f9a/bin/git-submit#L181)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

actually this is super useful: we could hop on the corresponding branch and just run `hub pr show -f %I`. That would mean we don't need to check or GITHUB_REPO_USER at all.
</blockquote></details>

Done.

**Review by pcorpet — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/165#-:-MZrp2kGDTa1F5P_HVf2:bnfp4nl)* status: Unresolved discussions (bin/git-submit:r2 line 39)

___
*[bin/git-submit, line 39 at r2](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/165#-MZroLTR4-QBDbbnK-3p:-MZroLTR4-QBDbbnK-3q:btumlpt) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/d08afbacde50d37ca17d314b4c6d3ced4e3b837e/bin/git-submit#L39)):*
> ```
> # to extract "bayesimpact" and "new-project".
> if [[ "$(git remote get-url "${BASE_REMOTE}")" =~ ^git@github.com:(.*)/(.*).git$ ]]; then
>   readonly GITHUB_REPO_USER="${BASH_REMATCH[1]}"
> ```

Add a TODO to rename this to a simple IS_GITHUB_REPO

**Review by zozoens31 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/165)* status: :shipit: complete! all files reviewed, 2 unresolved discussions

___
*[bin/git-submit, line 39 at r2](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/165#-MZroLTR4-QBDbbnK-3p:-MZrz4c-0vqplkglswRk:b-896fix) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/d08afbacde50d37ca17d314b4c6d3ced4e3b837e/bin/git-submit#L39)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

Add a TODO to rename this to a simple IS_GITHUB_REPO
</blockquote></details>

Done.

**Pull request merged**
