### PR TITLE
[Fix] Correct git submit when rev-parse exits with an error

### PR DESCRIPTION
**Pull request by emilieguth**
This change is [Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/160)

### CODE REVIEW

**Review by pcorpet — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/160)* status: LGTM missing from one of: pcorpet, Unresolved discussions (bin/git-submit:r1 line 25)

___
*[bin/git-submit, line 25 at r1](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/160#-MYCQDsiACAMJuEH2uyy:-MYCQDsiACAMJuEH2uyz:b-gz5zg1) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/3819bfb277a9a4730c8070a29a72a609d759e68e/bin/git-submit#L25)):*
> ```
> 
> # Usually main (and previously master).
> readonly ORIGIN_DEFAULT="$(git rev-parse --abbrev-ref "origin/HEAD")"
> ```

Note that you're using `origin` as the default, whereas later we compute BASE_REMOTE ...
___
*[bin/git-submit, line 35 at r1](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/160#-MYCPm5HD3TVxmjCs1ds:-MYCPm5I3_JJDgzCTD5n:b-5gbnki) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/3819bfb277a9a4730c8070a29a72a609d759e68e/bin/git-submit#L35)):*
> ```
>     GITHUB_REPO_USER="${BASH_REMATCH[1]}"
>     GITHUB_REPO_NAME="${BASH_REMATCH[2]}"
>     readonly DEFAULT_BRANCH="$(hub api repos/${GITHUB_REPO_USER}/${GITHUB_REPO_NAME} | jq -r .default_branch)"
> ```

Actually you don't need to get the repos use or name: `repos/{owner}/{repo}` is replaced by `hub` with the proper values directly.
___
*[bin/git-submit, line 153 at r1](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/160#-MYCPSZkDs4g4nW8Ew8e:-MYCPSZkDs4g4nW8Ew8f:breocv7) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/3819bfb277a9a4730c8070a29a72a609d759e68e/bin/git-submit#L153)):*
> ```
> if [ -z "${NO_SQUASH_ON_GITHUB}" ]; then
> 
>   if [-z "${GITHUB_REPO_USER}" ]; then
> ```

Please create a function instead of duplicating the computation.

**Review by pcorpet — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/160)* status: LGTM missing from one of: pcorpet, Unresolved discussions (bin/git-submit:r1 line 153)

___
*[bin/git-submit, line 38 at r1](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/160#-MYEKPhl5QlczQaZtc6L:-MYEKPhl5QlczQaZtc6M:bf38n2l) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/3819bfb277a9a4730c8070a29a72a609d759e68e/bin/git-submit#L38)):*
> ```
>   fi
> else
>   readonly DEFAULT_BRANCH="$(echo ${ORIGIN_DEFAULT} | cut -d/ -f2)"
> ```

Use `<<<`: `cut -d/ -f2 <<< "$ORIGIN_DEFAULT"`

**Review by pcorpet — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/160)* status: LGTM missing from one of: pcorpet, Unresolved discussions (bin/git-submit:r1 line 153)

___
*[bin/git-submit, line 26 at r1](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/160#-MYELtyHEN-PdRAG4mza:-MYELtyHEN-PdRAG4mzb:blnasbk) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/3819bfb277a9a4730c8070a29a72a609d759e68e/bin/git-submit#L26)):*
> ```
> # Usually main (and previously master).
> readonly ORIGIN_DEFAULT="$(git rev-parse --abbrev-ref "origin/HEAD")"
> if [ $? -ne 0 ]; then
> ```

The `readonly` command actually drops the error code
https://stackoverflow.com/questions/39696038/why-using-bash-readonly-variable-to-capture-output-fails-to-capture-return-code

Let's remove the readonly part

**Review by pcorpet — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/160)* status: LGTM missing from one of: pcorpet, Unresolved discussions (bin/git-submit:r1 line 153)

___
*[bin/git-submit, line 25 at r1](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/160#-MYEMAgd6rHP6m44bjNV:-MYEMAgd6rHP6m44bjNW:b7c8zel) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/3819bfb277a9a4730c8070a29a72a609d759e68e/bin/git-submit#L25)):*
> ```
> 
> # Usually main (and previously master).
> readonly ORIGIN_DEFAULT="$(git rev-parse --abbrev-ref "origin/HEAD")"
> ```

Please silent the git rev-parse with a trailing `2> /dev/null`

**Review by pcorpet — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/160)* status: LGTM missing from one of: pcorpet, Unresolved discussions (bin/git-submit:r1 line 153)

___
*[bin/git-submit, line 25 at r1](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/160#-MYF712ACaWvElWwi6e5:-MYF712B5RWBXTo99NWn:b-goigez) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/3819bfb277a9a4730c8070a29a72a609d759e68e/bin/git-submit#L25)):*
> ```
> 
> # Usually main (and previously master).
> readonly ORIGIN_DEFAULT="$(git rev-parse --abbrev-ref "origin/HEAD")"
> ```

Also I realize that what you're finding here is the main branch on distant repo, which might be named differently locally! So one should actually find the local branch that is tracking the distant one or rather change the logic below.

**Review by emilieguth — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/160)* status: LGTM missing from one of: pcorpet, Unresolved discussions (bin/git-submit:r1 line 25)

*[a discussion](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/160#-MYQ7FWI-HknU2qUDyfL:-MYQ7FWI-HknU2qUDyfM:bo0b08o) (no related file):*
Please note I just tested the script on Ma Voie (after cloning the repo again) and it worked as it is.

---
___
*[bin/git-submit, line 25 at r1](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/160#-MYEMAgd6rHP6m44bjNV:-MYPorwh1UXT6F4ZnpFL:b-896fix) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/3819bfb277a9a4730c8070a29a72a609d759e68e/bin/git-submit#L25)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

Please silent the git rev-parse with a trailing `2> /dev/null`
</blockquote></details>

Done.
___
*[bin/git-submit, line 25 at r1](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/160#-MYCQDsiACAMJuEH2uyy:-MYPt8WA4WyehNQJqFum:b-896fix) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/3819bfb277a9a4730c8070a29a72a609d759e68e/bin/git-submit#L25)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

Note that you're using `origin` as the default, whereas later we compute BASE_REMOTE ...
</blockquote></details>

Done.
___
*[bin/git-submit, line 25 at r1](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/160#-MYF712ACaWvElWwi6e5:-MYPuglq9yFB470fjjHj:b9323oi) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/3819bfb277a9a4730c8070a29a72a609d759e68e/bin/git-submit#L25)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

Also I realize that what you're finding here is the main branch on distant repo, which might be named differently locally! So one should actually find the local branch that is tracking the distant one or rather change the logic below.
</blockquote></details>

`BRANCH` is the local branch name.
___
*[bin/git-submit, line 26 at r1](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/160#-MYELtyHEN-PdRAG4mza:-MYPvEji-79pSYGRs8hE:b-896fix) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/3819bfb277a9a4730c8070a29a72a609d759e68e/bin/git-submit#L26)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

The `readonly` command actually drops the error code
https://stackoverflow.com/questions/39696038/why-using-bash-readonly-variable-to-capture-output-fails-to-capture-return-code

Let's remove the readonly part
</blockquote></details>

Done.
___
*[bin/git-submit, line 35 at r1](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/160#-MYCPm5HD3TVxmjCs1ds:-MYPv9iX66ILOkXWYpLL:b-896fix) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/3819bfb277a9a4730c8070a29a72a609d759e68e/bin/git-submit#L35)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

Actually you don't need to get the repos use or name: `repos/{owner}/{repo}` is replaced by `hub` with the proper values directly.
</blockquote></details>

Done.
___
*[bin/git-submit, line 38 at r1](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/160#-MYEKPhl5QlczQaZtc6L:-MYPvA276oTG4N6KCGo_:b-896fix) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/3819bfb277a9a4730c8070a29a72a609d759e68e/bin/git-submit#L38)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

Use `<<<`: `cut -d/ -f2 <<< "$ORIGIN_DEFAULT"`
</blockquote></details>

Done.
___
*[bin/git-submit, line 153 at r1](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/160#-MYCPSZkDs4g4nW8Ew8e:-MYPvpCE-7lhjv6lOrRr:b-896fix) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/3819bfb277a9a4730c8070a29a72a609d759e68e/bin/git-submit#L153)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

Please create a function instead of duplicating the computation.
</blockquote></details>

Done.

**Review by pcorpet — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/160)* status: LGTM missing from one of: pcorpet, Unresolved discussions (bin/git-submit:r1 line 25)

___
*[bin/git-submit, line 25 at r1](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/160#-MYF712ACaWvElWwi6e5:-MYR28467XR3UQ3c4bhu:b68zru2) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/3819bfb277a9a4730c8070a29a72a609d759e68e/bin/git-submit#L25)):*
<details><summary><i>Previously, emilieguth (Émilie Guth) wrote…</i></summary><blockquote>

`BRANCH` is the local branch name.
</blockquote></details>

My point is that what you use as DEFAULT_BRANCH is actually DEFAULT_REMOTE_BRANCH. see below
___
*[bin/git-submit, line 36 at r2](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/160#-MYR2i0Q0Tv6qDMCTnpC:-MYR2i0Q0Tv6qDMCTnpD:b-rbgml2) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/0c7cfe4fec9573701a88c09ff8d87d113f7e9849/bin/git-submit#L36)):*
> ```
> readonly BRANCH_REMOTE="$(git config "branch.${BRANCH}.remote")"
> 
> # The name of the remote used for default distant branch, usually "origin".
> ```

If you search for this one first, I'd actually list the remote and search for origin, bayes, bayesimpact if I cannot find any of these would just take the first orgin as BASE_REMOTE.
___
*[bin/git-submit, line 51 at r2](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/160#-MYR3bU1CQFrEDor38XU:-MYR3bU1CQFrEDor38XV:b98u9az) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/0c7cfe4fec9573701a88c09ff8d87d113f7e9849/bin/git-submit#L51)):*
> ```
> # The remote URL is "git@github.com:bayesimpact/new-project.git" and we want
> # to extract "bayesimpact" and "new-project".
> function get_repo_name_user {
> ```

This is kind of an anti pattern: calling a function that doesn't return anything and which main action is to create global variables.
___
*[bin/git-submit, line 53 at r2](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/160#-MYR2VzZ6es9xeZpkwHM:-MYR2Vz_BLdZMvfBnTHt:bnrhknb) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/0c7cfe4fec9573701a88c09ff8d87d113f7e9849/bin/git-submit#L53)):*
> ```
> function get_repo_name_user {
>   if [ -z "${GITHUB_REPO_USER}" ]; then
>     if [[ "$(git remote get-url "${BRANCH_REMOTE}")" =~ ^git@github.com:(.*)/(.*).git$ ]]; then
> ```

Did you mean BASE_REMOTE instead of BRANCH_REMOTE here?
___
*[bin/git-submit, line 65 at r2](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/160#-MYR2uwl8oDZxUkeRmsu:-MYR2uwl8oDZxUkeRmsv:bczug34) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/0c7cfe4fec9573701a88c09ff8d87d113f7e9849/bin/git-submit#L65)):*
> ```
>   get_repo_name_user
>   if [ -z "${GITHUB_REPO_USER}" ]; then
>     readonly DEFAULT_BRANCH="$(hub api repos/{owner}/{repo} | jq -r .default_branch)"
> ```

Here you're not taking the DEFAULT_BRANCH but the REMOTE_DEFAULT_BRANCH, you're missing an extra step to search for a local branch tracking it.

Theoritically I could have locally a branch named "master" that is tracking "origin/main". (git checkout -b master origin/main)
___
*[bin/git-submit, line 76 at r2](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/160#-MYR3QOkEOxodcWcRPKq:-MYR3QOkEOxodcWcRPKr:bw60fw7) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/270498382d8fdbc64ec23f384434a031b48e21ef/bin/git-submit#L76)):*
> ```
> readonly BRANCH_INITIAL="$(git rev-parse "${BRANCH}")"
> # The name of the remote tracked by this branch, usually "origin".
> readonly BRANCH_REMOTE="$(git config "branch.${BRANCH}.remote")"
> ```

Actually this one is quite useful: if the current branch is already tracking a remote, you could just decide that this is the correct remote to use.
___
*[bin/git-submit, line 187 at r2](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/160#-MYR3x-h1dJpEGRZApQ8:-MYR3x-h1dJpEGRZApQ9:b-lfqr10) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/0c7cfe4fec9573701a88c09ff8d87d113f7e9849/bin/git-submit#L187)):*
> ```
> 
>   # Ask GitHub to do the squash and merge!
>   hub api -X PUT "/repos/${GITHUB_REPO_USER}/${GITHUB_REPO_NAME}/pulls/${PULL_REQUEST_NUMBER}/merge" \
> ```

Here we could also use {repo} and {owner} so we don't have to compute it. which would allow us not to compute the REPO_NAME

**Review by emilieguth — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/160)* status: LGTM missing from one of: pcorpet, Unresolved discussions (bin/git-submit:r2 line 36)

___
*[bin/git-submit, line 25 at r1](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/160#-MYF712ACaWvElWwi6e5:-MYic9HX2XnU3h5xIc9O:b-896fix) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/3819bfb277a9a4730c8070a29a72a609d759e68e/bin/git-submit#L25)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

My point is that what you use as DEFAULT_BRANCH is actually DEFAULT_REMOTE_BRANCH. see below
</blockquote></details>

Done.
___
*[bin/git-submit, line 36 at r2](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/160#-MYR2i0Q0Tv6qDMCTnpC:-MYjDmKaCdkqhxqQ_3E3:bebptts) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/0c7cfe4fec9573701a88c09ff8d87d113f7e9849/bin/git-submit#L36)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

If you search for this one first, I'd actually list the remote and search for origin, bayes, bayesimpact if I cannot find any of these would just take the first orgin as BASE_REMOTE.
</blockquote></details>

I don't understand this one, when you have some time may we discuss about that please?
___
*[bin/git-submit, line 51 at r2](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/160#-MYR3bU1CQFrEDor38XU:-MYi_0qf7s3WgKZ_sU9T:b-896fix) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/0c7cfe4fec9573701a88c09ff8d87d113f7e9849/bin/git-submit#L51)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

This is kind of an anti pattern: calling a function that doesn't return anything and which main action is to create global variables.
</blockquote></details>

Done.
___
*[bin/git-submit, line 53 at r2](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/160#-MYR2VzZ6es9xeZpkwHM:-MYiZ2KQ5-shlXjZpCz2:b-896fix) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/0c7cfe4fec9573701a88c09ff8d87d113f7e9849/bin/git-submit#L53)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

Did you mean BASE_REMOTE instead of BRANCH_REMOTE here?
</blockquote></details>

Done.
___
*[bin/git-submit, line 65 at r2](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/160#-MYR2uwl8oDZxUkeRmsu:-MYjDGGl0J3AwA7hb-Ku:b-umh1s4) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/0c7cfe4fec9573701a88c09ff8d87d113f7e9849/bin/git-submit#L65)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

Here you're not taking the DEFAULT_BRANCH but the REMOTE_DEFAULT_BRANCH, you're missing an extra step to search for a local branch tracking it.

Theoritically I could have locally a branch named "master" that is tracking "origin/main". (git checkout -b master origin/main)
</blockquote></details>

Done. I think I managed to do something correct here.
___
*[bin/git-submit, line 76 at r2](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/160#-MYR3QOkEOxodcWcRPKq:-MYicow9Ck-hWUHl4_2O:bi863il) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/270498382d8fdbc64ec23f384434a031b48e21ef/bin/git-submit#L76)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

Actually this one is quite useful: if the current branch is already tracking a remote, you could just decide that this is the correct remote to use.
</blockquote></details>

Done. I just moved it at the top of the script as I use `BRANCH_REMOTE` upper.
___
*[bin/git-submit, line 187 at r2](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/160#-MYR3x-h1dJpEGRZApQ8:-MYicdbY1k2fiscHctch:b7qlvg7) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/0c7cfe4fec9573701a88c09ff8d87d113f7e9849/bin/git-submit#L187)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

Here we could also use {repo} and {owner} so we don't have to compute it. which would allow us not to compute the REPO_NAME
</blockquote></details>

Done. But I kept the `REPO_NAME` as it's used in the merge and squash command.

**Review by emilieguth — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/160)* status: LGTM missing from one of: pcorpet, Unresolved discussions (bin/git-submit:r2 line 36)

___
*[bin/git-submit, line 187 at r2](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/160#-MYR3x-h1dJpEGRZApQ8:-MYoxg3d-b-XfmSNG8WV:b2uzjal) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/0c7cfe4fec9573701a88c09ff8d87d113f7e9849/bin/git-submit#L187)):*
<details><summary><i>Previously, emilieguth (Émilie Guth) wrote…</i></summary><blockquote>

Done. But I kept the `REPO_NAME` as it's used in the merge and squash command.
</blockquote></details>

erratum the `GITHUB_REPO_USER` is used to retrieve the PR number. Sorry for my previous answer which was totally whatsoever!

**Review by pcorpet — APPROVED** [review]
> Reviewed 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/160)* status: LGTM missing from one of: pcorpet, Unresolved discussions (bin/git-submit:r5 line 38)

___
*[bin/git-submit, line 76 at r2](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/160#-MYR3QOkEOxodcWcRPKq:-MZHuA7q3sDZ2sX-RNOh:b1zpk6n) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/270498382d8fdbc64ec23f384434a031b48e21ef/bin/git-submit#L76)):*
<details><summary><i>Previously, emilieguth (Émilie Guth) wrote…</i></summary><blockquote>

Done. I just moved it at the top of the script as I use `BRANCH_REMOTE` upper.
</blockquote></details>

Please put it back now that you don't use it anymore.
___
*[bin/git-submit, line 38 at r5](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/160#-MZHEptiAvXcYCCmcGM2:-MZHEptiAvXcYCCmcGM3:b-7qnooa) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/9b06ddebd83f26270d06f3b664d9614a67c6da61/bin/git-submit#L38)):*
> ```
> # The remote URL is "git@github.com:bayesimpact/new-project.git" and we want
> # to extract "bayesimpact" and "new-project".
> if [ -z "${GITHUB_REPO_USER}" ]; then
> ```

Why would this one be set? you don't set it before, do you?
___
*[bin/git-submit, line 41 at r5](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/160#-MZHEloM8vNzVm_B-t7p:-MZHEloM8vNzVm_B-t7q:b4kukus) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/9b06ddebd83f26270d06f3b664d9614a67c6da61/bin/git-submit#L41)):*
> ```
>   if [[ "$(git remote get-url "${BASE_REMOTE}")" =~ ^git@github.com:(.*)/(.*).git$ ]]; then
>     readonly GITHUB_REPO_USER="${BASH_REMATCH[1]}"
>     readonly GITHUB_REPO_NAME="${BASH_REMATCH[2]}"
> ```

You never use this one, please drop.
___
*[bin/git-submit, line 60 at r5](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/160#-MZHsTai8jj9sTSAWCGn:-MZHsTai8jj9sTSAWCGo:b-fbkmu2) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/9b06ddebd83f26270d06f3b664d9614a67c6da61/bin/git-submit#L60)):*
> ```
> # Compute DEFAULT_BRANCH which is usually main (and previously master).
> # xargs is used to trim DEFAULT_REMOTE_OVERVIEW before cutting
> readonly DEFAULT_REMOTE_OVERVIEW="$(git branch -vv | grep ${BASE_REMOTE}/${DEFAULT_REMOTE_BRANCH} | xargs)"
> ```

Please use an approach that does not depend on git output (list all local branch, and for each one check the upstream, then take the first branch that had the proper upstream.

```sh
for branch in $(git for-each-ref --format='%(refname:short)' refs/heads); do
  if [ "$(git rev-parse --abbrev-ref $branch@{upstream} 2> /dev/null)" == "origin/master" ]; then
    echo $branch
    return
  fi
done
```

**Review by emilieguth — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/160)* status: LGTM missing from one of: pcorpet

___
*[bin/git-submit, line 76 at r2](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/160#-MYR3QOkEOxodcWcRPKq:-MZMlK7U3gyj7xlFXqrO:b-896fix) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/270498382d8fdbc64ec23f384434a031b48e21ef/bin/git-submit#L76)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

Please put it back now that you don't use it anymore.
</blockquote></details>

Done.
___
*[bin/git-submit, line 38 at r5](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/160#-MZHEptiAvXcYCCmcGM2:-MZMjduS-ForK2eeeBwT:buutbxt) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/9b06ddebd83f26270d06f3b664d9614a67c6da61/bin/git-submit#L38)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

Why would this one be set? you don't set it before, do you?
</blockquote></details>

Done. you're right!
___
*[bin/git-submit, line 41 at r5](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/160#-MZHEloM8vNzVm_B-t7p:-MZMjjpE28up8DsAvVQP:b-896fix) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/9b06ddebd83f26270d06f3b664d9614a67c6da61/bin/git-submit#L41)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

You never use this one, please drop.
</blockquote></details>

Done.
___
*[bin/git-submit, line 60 at r5](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/160#-MZHsTai8jj9sTSAWCGn:-MZMl4IuAcIXFXExdDsr:b-896fix) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/9b06ddebd83f26270d06f3b664d9614a67c6da61/bin/git-submit#L60)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

Please use an approach that does not depend on git output (list all local branch, and for each one check the upstream, then take the first branch that had the proper upstream.

```sh
for branch in $(git for-each-ref --format='%(refname:short)' refs/heads); do
  if [ "$(git rev-parse --abbrev-ref $branch@{upstream} 2> /dev/null)" == "origin/master" ]; then
    echo $branch
    return
  fi
done
```
</blockquote></details>

Done.

**Review by pcorpet — CHANGES_REQUESTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/160#-:-MZlELkF8H3V_fQ-6DDO:bnfp4nl)* status: Unresolved discussions (bin/git-submit:r6 line 114)

___
*[bin/git-submit, line 114 at r6](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/160#-MZlEC178N5buFQ2blAH:-MZlEC178N5buFQ2blAI:b-pkgn6s) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/b73fcb95e07ac53c87e80a5ca466f520f85cc75b/bin/git-submit#L114)):*
> ```
> readonly BRANCH_MERGE="$(git config "branch.${BRANCH}.merge" | sed -e s/^refs\\/heads\\///)"
> # The name of the remote tracked by this branch, usually "origin".
> readonly BRANCH_REMOTE="$(git config "branch.${BRANCH}.remote")"
> ```

Please put it just before BRANCH_MERGE so that the overall diff is cleaner (from r0)

**Review by emilieguth — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/160)* status: :shipit: complete! 2 of 3 files reviewed, 1 unresolved discussion

___
*[bin/git-submit, line 114 at r6](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/160#-MZlEC178N5buFQ2blAH:-MZmO_IND82QMceLt7QH:b-896fix) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/b73fcb95e07ac53c87e80a5ca466f520f85cc75b/bin/git-submit#L114)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

Please put it just before BRANCH_MERGE so that the overall diff is cleaner (from r0)
</blockquote></details>

Done.

**Pull request merged**
