### PR TITLE
Fix Docker registry login on OSX

### PR DESCRIPTION
**Pull request by everett-wetchler**
This change is [Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/16) &emsp; Multiple assignees:&emsp;@dedan&nbsp;<a href="/bayesimpact/bayes-developer-setup/pulls/assigned/dedan">dedan</a>,&emsp;@pcorpet&nbsp;<a href="/bayesimpact/bayes-developer-setup/pulls/assigned/pcorpet">pcorpet</a>

### CODE REVIEW

**Comment by pcorpet** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[fix_docker_osx_vm_config.py, line 1 \[r1\]](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/16#-KDUBRlN5-fbZTpFcZbz:-KDUBRlOOie1aBC9vtdl:744981238) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/afada058e1eae028fadbf10a293ecf72cb7c8fed/fix_docker_osx_vm_config.py#L1)):*
This is a lot of work for a one liner, we do the same thing for crontab and for shellrc.

sed -e "s/\(^\"Dns\".*\)null/\1[\"8.8.8.8\", \"8.8.4.4\"]/" -i $FILE

---

*[install.sh, line 87 \[r1\]](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/16#-KDU90AvcAC4InF37iKA:-KDU90AvcAC4InF37iKB:-631585176) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/afada058e1eae028fadbf10a293ecf72cb7c8fed/install.sh#L87)):*
Why do you install ruby on the machine? Ideally we should be only running Ruby in docker.

---

*[install.sh, line 91 \[r1\]](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/16#-KDU9xqvezOLBdMuoGg6:-KDU9xqvezOLBdMuoGg7:-254902199) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/afada058e1eae028fadbf10a293ecf72cb7c8fed/install.sh#L91)):*
This should happen  before the one above: I'm using brew up there.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/16)*

**Comment by everett-wetchler** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[install.sh, line 87 \[r1\]](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/16#-KDU90AvcAC4InF37iKA:-KDUVrF38rJOLnnHeKQl:-1973931965) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/afada058e1eae028fadbf10a293ecf72cb7c8fed/install.sh#L87)):*
Was for installing homebrew, but I can do that without Ruby. Changed.

---

*[install.sh, line 91 \[r1\]](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/16#-KDU9xqvezOLBdMuoGg6:-KDUcxBxwLMAVRFYTQLI:-499146009) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/afada058e1eae028fadbf10a293ecf72cb7c8fed/install.sh#L91)):*
Done.

---

*[fix_docker_osx_vm_config.py, line 1 \[r1\]](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/16#-KDUBRlN5-fbZTpFcZbz:-KDV-zYAYpOsoG3KaYnL:-499146009) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/afada058e1eae028fadbf10a293ecf72cb7c8fed/fix_docker_osx_vm_config.py#L1)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/16)*

**Comment by pcorpet** [comment]
+@dedan 

---

Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/16#-:-KDXid6jsTozqg_n4kgA:-550146966)*

**Comment by pcorpet** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[install.sh, line 78 \[r2\]](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/16#-KDXiuDbdEbniDva4w__:-KDXiuDbdEbniDva4w_a:-1744856995) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/345ead89cf091084f77d4e142d6b2bcea3ab6146/install.sh#L78)):*
shouldn't you do a $(wich docker-machine) instead?

---

*[install.sh, line 85 \[r2\]](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/16#-KDXj1B1PCZi_GEQsiL6:-KDXj1B2OZNYp-mMYrGH:-1368505107) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/345ead89cf091084f77d4e142d6b2bcea3ab6146/install.sh#L85)):*
Pretty cool, thanks for simplifying

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/16#-:-KDXj7-9FJMJA_cC6QY9:1417088721)*

**Comment by pcorpet** [comment]
+@pcorpet 

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/16#-:-KDXjHwxNjypYdJg_eDx:1879340593)*

**Comment by dedan** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/16#-:-KDYim45-udPxnUAbt-I:1417088721)*

**Pull request merged**
