### PR TITLE
[Easy Dev] Limit the number of requests to Github's API in git-submit.

### PR DESCRIPTION
**Pull request by zozoens31**
This change is [Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/188)

### CODE REVIEW

**Review by pcorpet — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/188)* status: LGTM missing from one of: pcorpet, Unresolved discussions (bin/git-submit:r1 line 104)

___
*[bin/git-submit, line 104 at r1](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/188#-M_tSCgg0KKXsuCqGcQj:-M_tSCgg0KKXsuCqGcQk:btq93fg) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/9e12184f72c75c48f8ace0cecc4a163e84feda7f/bin/git-submit#L104)):*
> ```
> }
> 
> function auto_mergeable_pr {
> ```

Let's not make that a function, just call gitHub API then set a PULL_REQUEST_AUTO_MERGEABLE

**Review by zozoens31 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/188)* status: LGTM missing from one of: pcorpet

___
*[bin/git-submit, line 104 at r1](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/188#-M_tSCgg0KKXsuCqGcQj:-M_tVLSH6ZcaWRV9gZXT:b-896fix) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/9e12184f72c75c48f8ace0cecc4a163e84feda7f/bin/git-submit#L104)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

Let's not make that a function, just call gitHub API then set a PULL_REQUEST_AUTO_MERGEABLE 
</blockquote></details>

Done.

**Review by pcorpet — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/188#-:-M_tavgBBsA8TXvBDBE0:bnfp4nl)* status: Unresolved discussions (bin/git-submit:r2 line 118)

___
*[bin/git-submit, line 118 at r2](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/188#-M_t_p6m4RSWPflAyDzl:-M_t_p6n8fSFKlDLWg7e:b-8x0xyr) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/8779db094c6ef6b831524f3439602e7b171864df/bin/git-submit#L118)):*
> ```
>     }' -F headRefName="$BRANCH_MERGE" |
>     jq '.data.repository.pullRequests.nodes[0]'
>   readonly PULL_REQUEST_NODE_ID="$(jq -r '.id' <<< "$result")"
> ```

Please drop those
___
*[bin/git-submit, line 130 at r2](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/188#-M_t_whH4xdSzTNUTuM3:-M_t_whH4xdSzTNUTuM4:b-o3q7x9) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/8779db094c6ef6b831524f3439602e7b171864df/bin/git-submit#L130)):*
> ```
>     else
>       echo "Continuous integration is \"${CI_STATUS}\""
>       readonly PR_INFO_JSON=$(mktmp -t "XXXXXX.json")
> ```

Please use`<<<` so that we don't need to remember to remove the file later.

**Review by zozoens31 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/188)* status: :shipit: complete! 0 of 1 files reviewed, 3 unresolved discussions

___
*[bin/git-submit, line 118 at r2](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/188#-M_t_p6m4RSWPflAyDzl:-M_tdZkC1kwlQCkzR3nX:b-896fix) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/8779db094c6ef6b831524f3439602e7b171864df/bin/git-submit#L118)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

Please drop those
</blockquote></details>

Done.
___
*[bin/git-submit, line 130 at r2](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/188#-M_t_whH4xdSzTNUTuM3:-M_tdaEc36K_VLqTLQI_:b-896fix) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/8779db094c6ef6b831524f3439602e7b171864df/bin/git-submit#L130)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

Please use`<<<` so that we don't need to remember to remove the file later.
</blockquote></details>

Done.

**Pull request merged**
