### PR TITLE
[Clean code] added an arg base branch

### PR DESCRIPTION
**Pull request by emilieguth**
This change is [Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/150)

### CODE REVIEW

**Review by zozoens31 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/150#-:-MT1FM4y1Obz0cAKxy5V:bnfp4nl)* status: Unresolved discussions (bin/git-review:r1 line 40)

___
*[bin/git-review, line 40 at r1](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/150#-MT1F_ITBW-qsVHqsfMW:-MT1F_ITBW-qsVHqsfMX:b-whp2qu) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/ae38bb82820cf4290c0e0b10ef3043b76cae11a3/bin/git-review#L40)):*
> ```
> 
> if [ -z "$BASE_BRANCH" ]; then
>   readonly BASE_BRANCH="$(git rev-parse --abbrev-ref "origin/HEAD" | cut -d/ -f2)"
> ```

please, use `$REMOTE_REPO` instead of `origin`

**Review by emilieguth — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/150)* status: :shipit: complete! 0 of 1 files reviewed, 1 unresolved discussion

___
*[bin/git-review, line 40 at r1](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/150#-MT1F_ITBW-qsVHqsfMW:-MT1HXAV5i61zhWXRiR6:b-896fix) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/ae38bb82820cf4290c0e0b10ef3043b76cae11a3/bin/git-review#L40)):*
<details><summary><i>Previously, zozoens31 (Cyrille Corpet) wrote…</i></summary><blockquote>

please, use `$REMOTE_REPO` instead of `origin`
</blockquote></details>

Done.

**Review by zozoens31 — CHANGES_REQUESTED** [review]
:lgtm_cancel:

> *[Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/150#-:-MT1TcZQCR7vcfWZFplH:bkw1etm)* status: LGTM missing from one of: zozoens31, Unresolved discussions (bin/git-review:r2 line 19)

___
*[bin/git-review, line 19 at r2](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/150#-MT1TlsM4KhZvq37JV1u:-MT1TlsM4KhZvq37JV1v:b3kwtl3) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/a99d69bb04a47bb1aef1d0f9e0ce62e36e52a74f/bin/git-review#L19)):*
> ```
>     shift # past value
>     ;;
>     -b|--base)
> ```

please, drop this (the previous behaviour was actually the right one). Just define `DEFAULT_BRANCH="$(git rev-parse --abbrev-ref "${REMOTE_REPO}/HEAD" | cut -d/ -f2)"` and use it wherever `master` was used

**Review by emilieguth — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/150)* status: LGTM missing from one of: zozoens31

___
*[bin/git-review, line 19 at r2](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/150#-MT1TlsM4KhZvq37JV1u:-MT2MlOT9iKnC2DN1GO7:b-896fix) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/a99d69bb04a47bb1aef1d0f9e0ce62e36e52a74f/bin/git-review#L19)):*
<details><summary><i>Previously, zozoens31 (Cyrille Corpet) wrote…</i></summary><blockquote>

please, drop this (the previous behaviour was actually the right one). Just define `DEFAULT_BRANCH="$(git rev-parse --abbrev-ref "${REMOTE_REPO}/HEAD" | cut -d/ -f2)"` and use it wherever `master` was used
</blockquote></details>

Done.

**Review by zozoens31 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/150)* status: LGTM missing from one of: zozoens31, Unresolved discussions (bin/git-review:r3 line 51)

___
*[bin/git-review, line 51 at r3](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/150#-MT52kc00768KP7IL6jL:-MT52kc159Fbx-2g2DQt:bco2g9i) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/d6bc2b01900ffd81070f55dbf5a1cfb8fb747110/bin/git-review#L51)):*
> ```
> fi
> 
> # Finds the best base branch.
> ```

please, keep this
___
*[bin/git-review, line 78 at r3](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/150#-MT5WMhRACx_6-XCCZaq:-MT5WMhRACx_6-XCCZar:bco2g9i) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/d6bc2b01900ffd81070f55dbf5a1cfb8fb747110/bin/git-review#L78)):*
> ```
> 
> # Ensures that there are some change to review.
> if [ -z "$(git diff $(git merge-base HEAD "${BASE_BRANCH}") --shortstat 2> /dev/null | tail -n1)" ]; then
> ```

please, keep this
___
*[bin/git-review, line 135 at r3](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/150#-MT5WRlo3o5RfL3EWx3X:-MT5WRlo3o5RfL3EWx3Y:bco2g9i) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/d6bc2b01900ffd81070f55dbf5a1cfb8fb747110/bin/git-review#L135)):*
> ```
>     # Create Merge Request.
>     gitlab project-merge-request create --project-id "$GITLAB_PROJECT_ID" \
>       --source-branch "$REMOTE_BRANCH" --target-branch "$REMOTE_BASE_BRANCH" \
> ```

please, keep this
___
*[bin/git-review, line 139 at r3](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/150#-MT5WT0hCekRWAFLJlCS:-MT5WT0hCekRWAFLJlCT:bco2g9i) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/d6bc2b01900ffd81070f55dbf5a1cfb8fb747110/bin/git-review#L139)):*
> ```
>   else
>     # GitHub
>     hub pull-request -F "${MESSAGE_FILE}" -a "${REVIEWER}" -r "${REVIEWER}" -h "${REMOTE_BRANCH}" -b "$REMOTE_BASE_BRANCH" | \
> ```

please, keep this

**Review by emilieguth — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/150)* status: LGTM missing from one of: zozoens31

___
*[bin/git-review, line 51 at r3](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/150#-MT52kc00768KP7IL6jL:-MT5xl_66w9Lgy4PkZhB:b-896fix) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/d6bc2b01900ffd81070f55dbf5a1cfb8fb747110/bin/git-review#L51)):*
<details><summary><i>Previously, zozoens31 (Cyrille Corpet) wrote…</i></summary><blockquote>

please, keep this
</blockquote></details>

Done.
___
*[bin/git-review, line 78 at r3](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/150#-MT5WMhRACx_6-XCCZaq:-MT5xm8iDqOnfkph9Dii:b-896fix) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/d6bc2b01900ffd81070f55dbf5a1cfb8fb747110/bin/git-review#L78)):*
<details><summary><i>Previously, zozoens31 (Cyrille Corpet) wrote…</i></summary><blockquote>

please, keep this
</blockquote></details>

Done.
___
*[bin/git-review, line 135 at r3](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/150#-MT5WRlo3o5RfL3EWx3X:-MT5xmvmAqkVcKwp5VOi:b-896fix) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/d6bc2b01900ffd81070f55dbf5a1cfb8fb747110/bin/git-review#L135)):*
<details><summary><i>Previously, zozoens31 (Cyrille Corpet) wrote…</i></summary><blockquote>

please, keep this
</blockquote></details>

Done.
___
*[bin/git-review, line 139 at r3](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/150#-MT5WT0hCekRWAFLJlCS:-MT5xnIaDZZkXnLz5cfj:b-896fix) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/d6bc2b01900ffd81070f55dbf5a1cfb8fb747110/bin/git-review#L139)):*
<details><summary><i>Previously, zozoens31 (Cyrille Corpet) wrote…</i></summary><blockquote>

please, keep this
</blockquote></details>

Done.

**Review by zozoens31 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/150#-:-MTBXgo2BfD-aIOnS2lT:bnfp4nl)* status: Unresolved discussions (bin/git-review:r4 line 106)

___
*[bin/git-review, line 78 at r4](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/150#-MTBXYeg9JNQyhkML8Jv:-MTBXYeg9JNQyhkML8Jw:b-h9w5pu) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/38038886db53e1e22b7393156e6d1ce9417b55fb/bin/git-review#L78)):*
> ```
> fi
> readonly BASE_BRANCH="$REMOTE_REPO/$REMOTE_BASE_BRANCH"
> ```

Nit. no need for this new line
___
*[bin/git-review, line 106 at r4](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/150#-MTBXbrJE6fbr8vfMvBm:-MTBXbrJE6fbr8vfMvBn:b68280n) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/38038886db53e1e22b7393156e6d1ce9417b55fb/bin/git-review#L106)):*
> ```
> readonly MESSAGE_FILE=$(mktemp)
> 
> git log "${REMOTE_REPO}/${DEFAULT_BRANCH}..${BRANCH}" --format=%B > "${MESSAGE_FILE}"
> ```

please, keep base branch here

**Review by emilieguth — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/150)* status: :shipit: complete! 0 of 1 files reviewed, 7 unresolved discussions

___
*[bin/git-review, line 106 at r4](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/150#-MTBXbrJE6fbr8vfMvBm:-MTFHXr-095J7F79_gOz:b-896fix) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/38038886db53e1e22b7393156e6d1ce9417b55fb/bin/git-review#L106)):*
<details><summary><i>Previously, zozoens31 (Cyrille Corpet) wrote…</i></summary><blockquote>

please, keep base branch here
</blockquote></details>

Done.

**Pull request merged**
