### PR TITLE
[Config] Use git config to store values, instead of environment.

### PR DESCRIPTION
**Pull request by zozoens31**
This change is [Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/266)

### CODE REVIEW

**Review by zozoens31 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/266)* status: LGTM missing from one of: pcorpet

___
*[install.sh, line 174 at r1](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/266#-MbjZ7-l3o-Sb9pxYUZw:-MbjZ7-l3o-Sb9pxYUZx:b-m3d6c5) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/55cb35418fae134664e14037677cec6389e61e8e/install.sh#L174)):*
> ```Shell
>   # TODO(cyrille): Add lint npm packages.
> fi
> ```

FYI, I'll tell engineers to run the following command:
```bash
sed -i '/Github engineers team/d' ~/.bashrc
```

**Review by pcorpet — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/266#-:-MbjnC146hE9bUbaw1a1:bnfp4nl)* status: Unresolved discussions (bin/git-review.py:r1 line 37)

___
*[bin/git-review.py, line 37 at r1](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/266#-Mbjlroh3XS6rgVLDch5:-Mbjlroh3XS6rgVLDch6:b3gwkhb) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/086a11a7e9ef5d01d5f430034c82b47a4b8c20c8/bin/git-review.py#L37)):*
> ```Python
> # Name of the remote to which the script pushes.
> _REMOTE_REPO = 'origin'
> # Slugged name for the Bayesimpact Github engineering team.
> ```

Bayes Impact (two words).
___
*[bin/git-review.py, line 88 at r1](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/266#-Mbjm1m8DZkQGdvjFToq:-Mbjm1m8DZkQGdvjFTor:b-stalxy) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/086a11a7e9ef5d01d5f430034c82b47a4b8c20c8/bin/git-review.py#L88)):*
> ```Python
> class _GitConfig:
> 
>     @property
> ```

maybe cache it with functools.property_cached?

**Review by zozoens31 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/266)* status: :shipit: complete! all files reviewed, 2 unresolved discussions

___
*[bin/git-review.py, line 37 at r1](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/266#-Mbjlroh3XS6rgVLDch5:-MbkNVLBC5WsFz-CfFW4:b-896fix) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/086a11a7e9ef5d01d5f430034c82b47a4b8c20c8/bin/git-review.py#L37)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

Bayes Impact (two words).
</blockquote></details>

Done.
___
*[bin/git-review.py, line 88 at r1](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/266#-Mbjm1m8DZkQGdvjFToq:-MbkNW4J6IRyylG6NQu9:b-826ob4) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/086a11a7e9ef5d01d5f430034c82b47a4b8c20c8/bin/git-review.py#L88)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

maybe cache it with functools.property_cached?
</blockquote></details>

Actually, I can't have a custom setter for a cached_property. It was a good suggestion, though...

**Comment by zozoens31** [comment]
:rocket:

**Pull request merged**
