### PR TITLE
[Hooks] Do not check empty init files in bazel diffs.

### PR DESCRIPTION
**Pull request by zozoens31**
This change is [Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/374)

### CODE REVIEW

**Comment by zozoens31** [comment]
:game_die:

**Comment by zozoens31** [comment]
:rocket:

**Comment by zozoens31** [comment]
:rocket:

**Review by pcorpet — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/374#-:-Mr2J3YACOCXaUMKi2sx:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
