### PR TITLE
[Install] Use a cleaner command to check for hub setup.

### PR DESCRIPTION
**Pull request by zozoens31**
This change is [Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/290)

### CODE REVIEW

**Comment by zozoens31** [comment]
:rocket:

**Review by emilieguth — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/290#-:-McFIh5Q6STgypFvnzGX:bnfp4nl)* status: Unresolved discussions (bin/git-review.py:r1 line 273)

___
*[bin/git-review.py, line 273 at r1](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/290#-McFIcr_4CNFdPP6wCnh:-McFIcraCFbjfrvvl8FF:b-zhhswn) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/d4f9a80b835f2ecc49f119b5de79150661541872/bin/git-review.py#L273)):*
> ```Python
> 
>         if _GIT_CONFIG.get_config('review.lucca.enabled') != 'true':
>             return None
> ```

This is not related.

**Review by zozoens31 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/290)* status: :shipit: complete! 0 of 2 files reviewed, 1 unresolved discussion

___
*[bin/git-review.py, line 273 at r1](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/290#-McFIcr_4CNFdPP6wCnh:-McG7or351YSHQMost0P:bnputky) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/d4f9a80b835f2ecc49f119b5de79150661541872/bin/git-review.py#L273)):*
<details><summary><i>Previously, emilieguth (Émilie Guth) wrote…</i></summary><blockquote>

This is not related.
</blockquote></details>

Done. Thanks

**Comment by zozoens31** [comment]
:rocket:

**Pull request merged**
