### PR TITLE
[Hooks] Ignore stdlib imports in bazel import diffs.

### PR DESCRIPTION
**Pull request by zozoens31**
This change is [Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/370)

### CODE REVIEW

**Comment by zozoens31** [comment]
:game_die:

**Comment by zozoens31** [comment]
:rocket:

**Review by pcorpet — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/370)* status: LGTM missing from one of: pcorpet, Unresolved discussions (hooks/pre-commit:r1 line 52)

___
*[hooks/pre-commit, line 52 at r1](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/370#-MqyrTZ80ObLVePR8y2T:-MqyrTZ80ObLVePR8y2U:b-4k5bkf) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/4f405d08d2504ccef0e0cb970e1d66d0e009f456/hooks/pre-commit#L52)):*
> ```
> 
> def _have_only_stdlib_imports(file: str) -> bool:
>     return all(
> ```

I'd rather list all libs before and all libs after and check that the diff is only on stdlibs

**Comment by zozoens31** [comment]
:rocket:

**Review by zozoens31 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/370)* status: LGTM missing from one of: pcorpet

___
*[hooks/pre-commit, line 52 at r1](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/370#-MqyrTZ80ObLVePR8y2T:-MqyzXri7NLphX1Irr0s:b-896fix) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/4f405d08d2504ccef0e0cb970e1d66d0e009f456/hooks/pre-commit#L52)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

I'd rather list all libs before and all libs after and check that the diff is only on stdlibs
</blockquote></details>

Done.

**Review by pcorpet — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/370#-:-Mr-Q0MaCDwVeGdJ9Jlt:bnfp4nl)* status: Unresolved discussions

*[a discussion](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/370#-Mr-PzJB0CaPGOTyAamp:-Mr-PzJDBtduOKYEDTks:blk4z18) (no related file):*
Please add a TODO to test that code.

---

**Comment by zozoens31** [comment]
:rocket:

**Review by zozoens31 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/370)* status: :shipit: complete! 1 of 2 files reviewed, 1 unresolved discussion

*[a discussion](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/370#-Mr-PzJB0CaPGOTyAamp:-Mr0xSbL1yUC_lnN5_wL:b-896fix) (no related file):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

Please add a TODO to test that code.
</blockquote></details>

Done.

---

**Pull request merged**
