### PR TITLE
[Submit] Add auto-completion to python git-submit.

### PR DESCRIPTION
**Pull request by zozoens31**
This change is [Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/358)

### CODE REVIEW

**Comment by zozoens31** [comment]
:game_die:

**Comment by zozoens31** [comment]
:game_die:

**Comment by zozoens31** [comment]
:rocket:

**Review by emilieguth — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/358#-:-MqTbq8x8D9M1KVtTwtG:bnfp4nl)* status: :shipit: complete! 0 of 2 files reviewed, all discussions resolved

**Pull request merged**
