### PR TITLE
Rename git review if hash in branch name

### PR DESCRIPTION
**Pull request by mlendale**
test #

---
This change is [Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/74)

### CODE REVIEW

**Comment by pcorpet** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/74#-KtVjUwaK4hWWyeTdVbv:-KtVjUwaK4hWWyeTdVbw:b-e96m89) (no related file):*
Please rephrase dash -> pound (or hash) in the commit message/PR description.

---

*[bin/git-review, line 22 at r1](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/74#-KtVj7_-Jxivro7K6dVP:-KtVj7_04iv2nuN4kg7p:bsyfz0w) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/aa243a30ec523e9d97e114d3828dcb5c160773ca/bin/git-review#L22)):*
> ```
> # Ensures that there are no invalid characters (i.e "#"") in branch name
> if [ -n "$(grep "#" <<< "${BRANCH}")" ]; then
>   echo "invalid character: # in branch name:" 1>&2
> ```

Let's capitalize our error.

---

*[bin/git-review, line 49 at r1](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/74#-KtVjKkxp6qOv5-nK96f:-KtVjKkxp6qOv5-nK96g:b-89upyg) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/aa243a30ec523e9d97e114d3828dcb5c160773ca/bin/git-review#L49)):*
> ```
>     exit 5
>   fi
>   readonly REMOTE_BRANCH="${USERNAME}-${BRANCH}"
> ```

This is where we create the remote branch, maybe we could only do an error here, or even drop the # from the local branch name so that it works magically.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/74)*

**Comment by mlendale** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/74#-KtVjUwaK4hWWyeTdVbv:-KtWS2jSXW_w2ITd6qQj:bb6un1j) (no related file):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

Please rephrase dash -> pound (or hash) in the commit message/PR description.
</blockquote></details>

Done

---

*[bin/git-review, line 22 at r1](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/74#-KtVj7_-Jxivro7K6dVP:-KtWNtLJg1c-FPNMOxKM:b-2j7pt) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/aa243a30ec523e9d97e114d3828dcb5c160773ca/bin/git-review#L22)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

Let's capitalize our error.
</blockquote></details>

No error anymore

---

*[bin/git-review, line 49 at r1](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/74#-KtVjKkxp6qOv5-nK96f:-KtWNv4Xb-aSP39RgFz5:b-896fix) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/aa243a30ec523e9d97e114d3828dcb5c160773ca/bin/git-review#L49)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

This is where we create the remote branch, maybe we could only do an error here, or even drop the # from the local branch name so that it works magically.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/74)*

**Comment by pcorpet** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/74#-KtVjUwaK4hWWyeTdVbv:-KtWTvScE4UpDVyodqVN:bulygo3) (no related file):*
<details><summary><i>Previously, mlendale (Marie Laure Endale Ahanda) wrote…</i></summary><blockquote>

Done
</blockquote></details>

Is it?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/74#-:-KtWUJjZva_O2plEUnQY:bnfp4nl)*

**Comment by mlendale** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/74#-KtVjUwaK4hWWyeTdVbv:-KtWVI0QV34tL0ZsmLsB:b-he7pj4) (no related file):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

Is it?
</blockquote></details>

Isn't it?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bayesimpact/bayes-developer-setup/74)*

**Pull request merged**
