### PR TITLE
[Hooks] Run Bazel locally on pre-commit hook.

### PR DESCRIPTION
**Pull request by zozoens31**
This change is [Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/344)

### CODE REVIEW

**Comment by zozoens31** [comment]
:rocket:

**Review by pcorpet — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/344#-:-MpqF8yn9Wb-f8Cgp7EV:bnfp4nl)* status: Unresolved discussions (hooks/pre-commit:r1 line 59)

___
*[hooks/pre-commit, line 59 at r1](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/344#-MpqF5_N84Qh-0Gq4hOt:-MpqF5_N84Qh-0Gq4hOu:b96dkhy) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/fa159f47675bd651744ab410a7439e2c19f05aed/hooks/pre-commit#L59)):*
> ```
>     return
>   fi
>   if ! bazel query 'deps(//...)' > /dev/null; then
> ```

Please run only the .circleci/...

**Comment by zozoens31** [comment]
:rocket:

**Review by zozoens31 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/344)* status: :shipit: complete! 0 of 1 files reviewed, 1 unresolved discussion

___
*[hooks/pre-commit, line 59 at r1](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/344#-MpqF5_N84Qh-0Gq4hOt:-MpsVPLzAcQw_GfnE258:b-896fix) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/fa159f47675bd651744ab410a7439e2c19f05aed/hooks/pre-commit#L59)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

Please run only the .circleci/...
</blockquote></details>

Done.

**Pull request merged**
