### PR TITLE
[Reviewers] Request reviews from engineers only.

### PR DESCRIPTION
**Pull request by zozoens31**
This change is [Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/254)

### CODE REVIEW

**Comment by zozoens31** [comment]
+@mlendale +@emilieguth

**Review by pcorpet — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/254#-:-Mba18zU1vVXPt8W7R5p:bnfp4nl)* status: Unresolved discussions

*[a discussion](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/254#-Mba0rJJ7dObyqy7vtQB:-Mba0rJJ7dObyqy7vtQC:b-cez6s3) (no related file):*
Please document somewhere the difference that you're introducing about reviewer vs assignee

---
___
*[install.sh, line 112 at r2](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/254#-Mba-vAk2h3SBiAlbGiZ:-Mba-vAl8P8ADQUjF_7K:bupwgpl) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/31ce0f493e2a1c93c4d0087ae53802a1f90538ca/install.sh#L112)):*
> ```Shell
>   elif brew list bash-completion@2; then
>     AUTOCOMPLETE_PATH="/usr/local/share/bash-completion/completions"
>   fi
> ```

Not related
___
*[install.sh, line 175 at r2](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/254#-Mba0L9u-3zlmG25KRIG:-Mba0L9u-3zlmG25KRIH:b8vs2j9) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/31ce0f493e2a1c93c4d0087ae53802a1f90538ca/install.sh#L175)):*
> ```Shell
> fi
> 
> if hub ci-status > /dev/null && jq --version > /dev/null; then
> ```

`hub ci-status` would fail if the CI is not succesful for the current commit. Please add a TODO to fix this (here and above as well).

**Review by zozoens31 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/254)* status: :shipit: complete! 2 of 3 files reviewed, 2 unresolved discussions

*[a discussion](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/254#-Mba0rJJ7dObyqy7vtQB:-MbaCPGI5bwa-Dm43zHu:b-896fix) (no related file):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

Please document somewhere the difference that you're introducing about reviewer vs assignee
</blockquote></details>

Done.

---
___
*[install.sh, line 175 at r2](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/254#-Mba0L9u-3zlmG25KRIG:-MbaBChRCi1CWlW7NdcR:b-896fix) ([raw file](https://github.com/bayesimpact/bayes-developer-setup/blob/31ce0f493e2a1c93c4d0087ae53802a1f90538ca/install.sh#L175)):*
<details><summary><i>Previously, pcorpet (Pascal Corpet) wrote…</i></summary><blockquote>

`hub ci-status` would fail if the CI is not succesful for the current commit. Please add a TODO to fix this (here and above as well).
</blockquote></details>

Done.

**Comment by zozoens31** [comment]
:rocket:

**Pull request merged**
